// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AiGatewayToken ai gateway token
//
// swagger:model aiGatewayToken
type AiGatewayToken struct {

	// Unix timestamp when the token expires
	ExpiresAt int64 `json:"expires_at,omitempty"`

	// The AI Gateway authentication token
	Token string `json:"token,omitempty"`

	// AI gateway base url
	URL string `json:"url,omitempty"`
}

// Validate validates this ai gateway token
func (m *AiGatewayToken) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AiGatewayToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AiGatewayToken) UnmarshalBinary(b []byte) error {
	var res AiGatewayToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
