package models

import "github.com/go-openapi/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*AssetPublicSignature asset public signature

swagger:model assetPublicSignature
*/
type AssetPublicSignature struct {

	/* url
	 */
	URL string `json:"url,omitempty"`
}

// Validate validates this asset public signature
func (m *AssetPublicSignature) Validate(formats strfmt.Registry) error {
	return nil
}
