// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BuildStatus build status
//
// swagger:model buildStatus
type BuildStatus struct {

	// active
	Active int64 `json:"active,omitempty"`

	// build count
	BuildCount int64 `json:"build_count,omitempty"`

	// enqueued
	Enqueued int64 `json:"enqueued,omitempty"`

	// minutes
	Minutes *BuildStatusMinutes `json:"minutes,omitempty"`

	// pending concurrency
	PendingConcurrency int64 `json:"pending_concurrency,omitempty"`
}

// Validate validates this build status
func (m *BuildStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMinutes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BuildStatus) validateMinutes(formats strfmt.Registry) error {

	if swag.IsZero(m.Minutes) { // not required
		return nil
	}

	if m.Minutes != nil {
		if err := m.Minutes.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("minutes")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BuildStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildStatus) UnmarshalBinary(b []byte) error {
	var res BuildStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
