// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DatabaseMigrationDetail A migration with its file contents
//
// swagger:model databaseMigrationDetail
type DatabaseMigrationDetail struct {

	// The raw contents of the migration file
	Content string `json:"content,omitempty"`

	// The migration name
	Name string `json:"name,omitempty"`

	// The path to the migration file in the deploy bundle
	Path string `json:"path,omitempty"`

	// The migration version number
	Version int64 `json:"version,omitempty"`
}

// Validate validates this database migration detail
func (m *DatabaseMigrationDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DatabaseMigrationDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DatabaseMigrationDetail) UnmarshalBinary(b []byte) error {
	var res DatabaseMigrationDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
