package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

/*Deploy deploy

swagger:model deploy
*/
type Deploy struct {

	/* created at
	 */
	CreatedAt string `json:"created_at,omitempty"`

	/* deploy url
	 */
	DeployURL string `json:"deploy_url,omitempty"`

	/* id
	 */
	ID string `json:"id,omitempty"`

	/* required
	 */
	Required []string `json:"required,omitempty"`

	/* screenshot url
	 */
	ScreenshotURL string `json:"screenshot_url,omitempty"`

	/* site id
	 */
	SiteID string `json:"site_id,omitempty"`

	/* site url
	 */
	SiteURL string `json:"site_url,omitempty"`

	/* state
	 */
	State string `json:"state,omitempty"`

	/* updated at
	 */
	UpdatedAt string `json:"updated_at,omitempty"`

	/* user id
	 */
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this deploy
func (m *Deploy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRequired(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Deploy) validateRequired(formats strfmt.Registry) error {

	if swag.IsZero(m.Required) { // not required
		return nil
	}

	return nil
}
