// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeployValidationsReport deploy validations report
//
// swagger:model DeployValidationsReport
type DeployValidationsReport struct {

	// The id of the deploy
	DeployID string `json:"deploy_id,omitempty"`

	// The id of the deploy validations report
	ID string `json:"id,omitempty"`

	// secret scan result
	SecretScanResult *DeployValidationsReportSecretScanResult `json:"secret_scan_result,omitempty"`
}

// Validate validates this deploy validations report
func (m *DeployValidationsReport) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSecretScanResult(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeployValidationsReport) validateSecretScanResult(formats strfmt.Registry) error {

	if swag.IsZero(m.SecretScanResult) { // not required
		return nil
	}

	if m.SecretScanResult != nil {
		if err := m.SecretScanResult.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("secret_scan_result")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeployValidationsReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeployValidationsReport) UnmarshalBinary(b []byte) error {
	var res DeployValidationsReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
