// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeployEnvironmentVariable deploy environment variable
//
// swagger:model deployEnvironmentVariable
type DeployEnvironmentVariable struct {

	// is secret
	// Required: true
	IsSecret *bool `json:"is_secret"`

	// key
	// Required: true
	Key *string `json:"key"`

	// scopes
	// Required: true
	Scopes []string `json:"scopes"`

	// value
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this deploy environment variable
func (m *DeployEnvironmentVariable) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIsSecret(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScopes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeployEnvironmentVariable) validateIsSecret(formats strfmt.Registry) error {

	if err := validate.Required("is_secret", "body", m.IsSecret); err != nil {
		return err
	}

	return nil
}

func (m *DeployEnvironmentVariable) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

var deployEnvironmentVariableScopesItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["builds","functions","runtime","post-processing"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		deployEnvironmentVariableScopesItemsEnum = append(deployEnvironmentVariableScopesItemsEnum, v)
	}
}

func (m *DeployEnvironmentVariable) validateScopesItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, deployEnvironmentVariableScopesItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DeployEnvironmentVariable) validateScopes(formats strfmt.Registry) error {

	if err := validate.Required("scopes", "body", m.Scopes); err != nil {
		return err
	}

	for i := 0; i < len(m.Scopes); i++ {

		// value enum
		if err := m.validateScopesItemsEnum("scopes"+"."+strconv.Itoa(i), "body", m.Scopes[i]); err != nil {
			return err
		}

	}

	return nil
}

func (m *DeployEnvironmentVariable) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeployEnvironmentVariable) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeployEnvironmentVariable) UnmarshalBinary(b []byte) error {
	var res DeployEnvironmentVariable
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
