// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeployFiles Deploy files can be provided in two ways:
// 1. As a JSON object using 'files' (a hash mapping file paths to SHA1 digests), OR
// 2. As a zip file using one of these methods:
//   - Set Content-Type to 'application/zip' and send the zip file as the raw request body
//   - Include the zip file content in the 'zip' field of this JSON object with Content-Type 'application/json'
//
// swagger:model deployFiles
type DeployFiles struct {

	// async
	Async bool `json:"async,omitempty"`

	// branch
	Branch string `json:"branch,omitempty"`

	// draft
	Draft bool `json:"draft,omitempty"`

	// A list of deploy-specific environment variable data. Data specified this way applies only
	// to this specific deploy and is merged into any existing environment variables set on the
	// account and site.
	//
	// Deploy-specific environment variable data takes precedence over account and site
	// environment variable data: For example, a deploy-specific variable with the key `NODE_ENV`
	// will take priority over any existing site- and account-level environment variable data
	// with the key `NODE_ENV`.
	//
	// Environment variable data may be provided at one of two times:
	//
	// - When creating a new Deploy with deploy files (most common)
	// - When finalizing an existing Deploy with deploy files
	//
	// Once set, environment variables for a specific deploy cannot be modified. Subsequent
	// attempts to modify environment variable data for a deploy will be ignored.
	//
	Environment []*DeployEnvironmentVariable `json:"environment"`

	// A hash mapping file paths to SHA1 digests of the file contents.
	Files interface{} `json:"files,omitempty"`

	// framework
	Framework string `json:"framework,omitempty"`

	// framework version
	FrameworkVersion string `json:"framework_version,omitempty"`

	// function schedules
	FunctionSchedules []*FunctionSchedule `json:"function_schedules"`

	// functions
	Functions interface{} `json:"functions,omitempty"`

	// functions config
	FunctionsConfig map[string]FunctionConfig `json:"functions_config,omitempty"`

	// A zip file containing the site files to deploy. Alternative to 'files'.
	// To use this field, set Content-Type to 'application/json' and include the zip content here.
	// Alternatively, you can set Content-Type to 'application/zip' and send the zip as the raw request body (not as JSON).
	//
	// Format: binary
	Zip io.ReadCloser `json:"zip,omitempty"`
}

// Validate validates this deploy files
func (m *DeployFiles) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEnvironment(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFunctionSchedules(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFunctionsConfig(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeployFiles) validateEnvironment(formats strfmt.Registry) error {

	if swag.IsZero(m.Environment) { // not required
		return nil
	}

	for i := 0; i < len(m.Environment); i++ {
		if swag.IsZero(m.Environment[i]) { // not required
			continue
		}

		if m.Environment[i] != nil {
			if err := m.Environment[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("environment" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeployFiles) validateFunctionSchedules(formats strfmt.Registry) error {

	if swag.IsZero(m.FunctionSchedules) { // not required
		return nil
	}

	for i := 0; i < len(m.FunctionSchedules); i++ {
		if swag.IsZero(m.FunctionSchedules[i]) { // not required
			continue
		}

		if m.FunctionSchedules[i] != nil {
			if err := m.FunctionSchedules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("function_schedules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *DeployFiles) validateFunctionsConfig(formats strfmt.Registry) error {

	if swag.IsZero(m.FunctionsConfig) { // not required
		return nil
	}

	for k := range m.FunctionsConfig {

		if err := validate.Required("functions_config"+"."+k, "body", m.FunctionsConfig[k]); err != nil {
			return err
		}
		if val, ok := m.FunctionsConfig[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DeployFiles) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeployFiles) UnmarshalBinary(b []byte) error {
	var res DeployFiles
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
