// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListDatabaseMigrationsResponse Response containing the list of migrations for a branch
//
// swagger:model listDatabaseMigrationsResponse
type ListDatabaseMigrationsResponse struct {

	// List of migrations
	Migrations []*DatabaseMigration `json:"migrations"`
}

// Validate validates this list database migrations response
func (m *ListDatabaseMigrationsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMigrations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ListDatabaseMigrationsResponse) validateMigrations(formats strfmt.Registry) error {

	if swag.IsZero(m.Migrations) { // not required
		return nil
	}

	for i := 0; i < len(m.Migrations); i++ {
		if swag.IsZero(m.Migrations[i]) { // not required
			continue
		}

		if m.Migrations[i] != nil {
			if err := m.Migrations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("migrations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ListDatabaseMigrationsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ListDatabaseMigrationsResponse) UnmarshalBinary(b []byte) error {
	var res ListDatabaseMigrationsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
