// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MinifyOptions minify options
//
// swagger:model minifyOptions
type MinifyOptions struct {

	// bundle
	Bundle bool `json:"bundle,omitempty"`

	// minify
	Minify bool `json:"minify,omitempty"`
}

// Validate validates this minify options
func (m *MinifyOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MinifyOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MinifyOptions) UnmarshalBinary(b []byte) error {
	var res MinifyOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
