// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UserOnboardingProgress user onboarding progress
//
// swagger:model userOnboardingProgress
type UserOnboardingProgress struct {

	// slides
	Slides string `json:"slides,omitempty"`
}

// Validate validates this user onboarding progress
func (m *UserOnboardingProgress) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UserOnboardingProgress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserOnboardingProgress) UnmarshalBinary(b []byte) error {
	var res UserOnboardingProgress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
