package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSiteSnippetParams creates a new GetSiteSnippetParams object
// with the default values initialized.
func NewGetSiteSnippetParams() *GetSiteSnippetParams {
	var ()
	return &GetSiteSnippetParams{}
}

/*GetSiteSnippetParams contains all the parameters to send to the API endpoint
for the get site snippet operation typically these are written to a http.Request
*/
type GetSiteSnippetParams struct {

	/*SiteID*/
	SiteID string
	/*SnippetID*/
	SnippetID string
}

// WithSiteID adds the siteId to the get site snippet params
func (o *GetSiteSnippetParams) WithSiteID(SiteID string) *GetSiteSnippetParams {
	o.SiteID = SiteID
	return o
}

// WithSnippetID adds the snippetId to the get site snippet params
func (o *GetSiteSnippetParams) WithSnippetID(SnippetID string) *GetSiteSnippetParams {
	o.SnippetID = SnippetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSiteSnippetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param snippet_id
	if err := r.SetPathParam("snippet_id", o.SnippetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
