package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewProvisionSiteSSLParams creates a new ProvisionSiteSSLParams object
// with the default values initialized.
func NewProvisionSiteSSLParams() *ProvisionSiteSSLParams {
	var ()
	return &ProvisionSiteSSLParams{}
}

/*ProvisionSiteSSLParams contains all the parameters to send to the API endpoint
for the provision site s s l operation typically these are written to a http.Request
*/
type ProvisionSiteSSLParams struct {

	/*SiteID*/
	SiteID string
}

// WithSiteID adds the siteId to the provision site s s l params
func (o *ProvisionSiteSSLParams) WithSiteID(SiteID string) *ProvisionSiteSSLParams {
	o.SiteID = SiteID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ProvisionSiteSSLParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
