/**
 * Netlify's API definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.NetlifysApiDefinition) {
      root.NetlifysApiDefinition = {};
    }
    root.NetlifysApiDefinition.AccountUpdateSetup = factory(root.NetlifysApiDefinition.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AccountUpdateSetup model module.
   * @module model/AccountUpdateSetup
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>AccountUpdateSetup</code>.
   * @alias module:model/AccountUpdateSetup
   * @class
   */
  var exports = function() {
    var _this = this;









  };

  /**
   * Constructs a <code>AccountUpdateSetup</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AccountUpdateSetup} obj Optional instance to populate.
   * @return {module:model/AccountUpdateSetup} The populated <code>AccountUpdateSetup</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('slug')) {
        obj['slug'] = ApiClient.convertToType(data['slug'], 'String');
      }
      if (data.hasOwnProperty('type_id')) {
        obj['type_id'] = ApiClient.convertToType(data['type_id'], 'String');
      }
      if (data.hasOwnProperty('payment_method_id')) {
        obj['payment_method_id'] = ApiClient.convertToType(data['payment_method_id'], 'String');
      }
      if (data.hasOwnProperty('extra_seats_block')) {
        obj['extra_seats_block'] = ApiClient.convertToType(data['extra_seats_block'], 'Number');
      }
      if (data.hasOwnProperty('billing_name')) {
        obj['billing_name'] = ApiClient.convertToType(data['billing_name'], 'String');
      }
      if (data.hasOwnProperty('billing_email')) {
        obj['billing_email'] = ApiClient.convertToType(data['billing_email'], 'String');
      }
      if (data.hasOwnProperty('billing_details')) {
        obj['billing_details'] = ApiClient.convertToType(data['billing_details'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} slug
   */
  exports.prototype['slug'] = undefined;
  /**
   * @member {String} type_id
   */
  exports.prototype['type_id'] = undefined;
  /**
   * @member {String} payment_method_id
   */
  exports.prototype['payment_method_id'] = undefined;
  /**
   * @member {Number} extra_seats_block
   */
  exports.prototype['extra_seats_block'] = undefined;
  /**
   * @member {String} billing_name
   */
  exports.prototype['billing_name'] = undefined;
  /**
   * @member {String} billing_email
   */
  exports.prototype['billing_email'] = undefined;
  /**
   * @member {String} billing_details
   */
  exports.prototype['billing_details'] = undefined;



  return exports;
}));


