/**
 * Netlify's API definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/UserOnboardingProgress'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserOnboardingProgress'));
  } else {
    // Browser globals (root is window)
    if (!root.NetlifysApiDefinition) {
      root.NetlifysApiDefinition = {};
    }
    root.NetlifysApiDefinition.User = factory(root.NetlifysApiDefinition.ApiClient, root.NetlifysApiDefinition.UserOnboardingProgress);
  }
}(this, function(ApiClient, UserOnboardingProgress) {
  'use strict';




  /**
   * The User model module.
   * @module model/User
   * @version 0.2.0
   */

  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'String');
      }
      if (data.hasOwnProperty('uid')) {
        obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
      }
      if (data.hasOwnProperty('full_name')) {
        obj['full_name'] = ApiClient.convertToType(data['full_name'], 'String');
      }
      if (data.hasOwnProperty('avatar_url')) {
        obj['avatar_url'] = ApiClient.convertToType(data['avatar_url'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('affiliate_id')) {
        obj['affiliate_id'] = ApiClient.convertToType(data['affiliate_id'], 'String');
      }
      if (data.hasOwnProperty('site_count')) {
        obj['site_count'] = ApiClient.convertToType(data['site_count'], 'Number');
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('last_login')) {
        obj['last_login'] = ApiClient.convertToType(data['last_login'], 'String');
      }
      if (data.hasOwnProperty('login_providers')) {
        obj['login_providers'] = ApiClient.convertToType(data['login_providers'], ['String']);
      }
      if (data.hasOwnProperty('onboarding_progress')) {
        obj['onboarding_progress'] = UserOnboardingProgress.constructFromObject(data['onboarding_progress']);
      }
      if (data.hasOwnProperty('support_priority')) {
        obj['support_priority'] = ApiClient.convertToType(data['support_priority'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} uid
   */
  exports.prototype['uid'] = undefined;
  /**
   * @member {String} full_name
   */
  exports.prototype['full_name'] = undefined;
  /**
   * @member {String} avatar_url
   */
  exports.prototype['avatar_url'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} affiliate_id
   */
  exports.prototype['affiliate_id'] = undefined;
  /**
   * @member {Number} site_count
   */
  exports.prototype['site_count'] = undefined;
  /**
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * @member {String} last_login
   */
  exports.prototype['last_login'] = undefined;
  /**
   * @member {Array.<String>} login_providers
   */
  exports.prototype['login_providers'] = undefined;
  /**
   * @member {module:model/UserOnboardingProgress} onboarding_progress
   */
  exports.prototype['onboarding_progress'] = undefined;
  /**
   * @member {Number} support_priority
   */
  exports.prototype['support_priority'] = undefined;



  return exports;
}));


