/*
Package plumbing provides a Go client for accessing Netlify's API. It is autogenerated by go-swagger.

See https://goswagger.io/generate/client.html for more example usage of an API client generated by go-swagger.
*/
package plumbing

import (
	"fmt"
	"log"
	"net/http"
	"net/http/httptest"
	"strings"

	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/netlify/open-api/go/plumbing/operations"
)

func Example() {
	server := httptest.NewServer(http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		rw.Header().Set("Content-Type", "application/json; charset=utf-8")
		rw.Write([]byte(`{ "name": "Pets of Netlify" }`))
	}))
	defer server.Close()
	host := strings.ReplaceAll(server.URL, "http://", "")

	// For Netlify's production API use DefaultHost, DefaultBasePath, DefaultSchemes
	transport := httptransport.New(host, DefaultBasePath, []string{"http"})
	client := New(transport, strfmt.Default)

	authInfo := runtime.ClientAuthInfoWriterFunc(func(r runtime.ClientRequest, _ strfmt.Registry) error {
		r.SetHeaderParam("User-Agent", "Your app")
		r.SetHeaderParam("Authorization", "Bearer your_netlify_api_token")
		return nil
	})

	params := operations.NewGetSiteParams()
	params.SiteID = "123"
	res, err := client.Operations.GetSite(params, authInfo)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(res.Payload.Name)
	// Output: Pets of Netlify
}
