// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// AgentRunnerPullRequestReader is a Reader for the AgentRunnerPullRequest structure.
type AgentRunnerPullRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AgentRunnerPullRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAgentRunnerPullRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAgentRunnerPullRequestBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAgentRunnerPullRequestConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewAgentRunnerPullRequestUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewAgentRunnerPullRequestDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewAgentRunnerPullRequestOK creates a AgentRunnerPullRequestOK with default headers values
func NewAgentRunnerPullRequestOK() *AgentRunnerPullRequestOK {
	return &AgentRunnerPullRequestOK{}
}

/*
AgentRunnerPullRequestOK handles this case with default header values.

OK
*/
type AgentRunnerPullRequestOK struct {
}

func (o *AgentRunnerPullRequestOK) Error() string {
	return fmt.Sprintf("[POST /agent_runners/{agent_runner_id}/pull_request][%d] agentRunnerPullRequestOK ", 200)
}

func (o *AgentRunnerPullRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAgentRunnerPullRequestBadRequest creates a AgentRunnerPullRequestBadRequest with default headers values
func NewAgentRunnerPullRequestBadRequest() *AgentRunnerPullRequestBadRequest {
	return &AgentRunnerPullRequestBadRequest{}
}

/*
AgentRunnerPullRequestBadRequest handles this case with default header values.

Bad Request
*/
type AgentRunnerPullRequestBadRequest struct {
}

func (o *AgentRunnerPullRequestBadRequest) Error() string {
	return fmt.Sprintf("[POST /agent_runners/{agent_runner_id}/pull_request][%d] agentRunnerPullRequestBadRequest ", 400)
}

func (o *AgentRunnerPullRequestBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAgentRunnerPullRequestConflict creates a AgentRunnerPullRequestConflict with default headers values
func NewAgentRunnerPullRequestConflict() *AgentRunnerPullRequestConflict {
	return &AgentRunnerPullRequestConflict{}
}

/*
AgentRunnerPullRequestConflict handles this case with default header values.

Conflict
*/
type AgentRunnerPullRequestConflict struct {
}

func (o *AgentRunnerPullRequestConflict) Error() string {
	return fmt.Sprintf("[POST /agent_runners/{agent_runner_id}/pull_request][%d] agentRunnerPullRequestConflict ", 409)
}

func (o *AgentRunnerPullRequestConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAgentRunnerPullRequestUnprocessableEntity creates a AgentRunnerPullRequestUnprocessableEntity with default headers values
func NewAgentRunnerPullRequestUnprocessableEntity() *AgentRunnerPullRequestUnprocessableEntity {
	return &AgentRunnerPullRequestUnprocessableEntity{}
}

/*
AgentRunnerPullRequestUnprocessableEntity handles this case with default header values.

Unprocessable Entity
*/
type AgentRunnerPullRequestUnprocessableEntity struct {
}

func (o *AgentRunnerPullRequestUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /agent_runners/{agent_runner_id}/pull_request][%d] agentRunnerPullRequestUnprocessableEntity ", 422)
}

func (o *AgentRunnerPullRequestUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAgentRunnerPullRequestDefault creates a AgentRunnerPullRequestDefault with default headers values
func NewAgentRunnerPullRequestDefault(code int) *AgentRunnerPullRequestDefault {
	return &AgentRunnerPullRequestDefault{
		_statusCode: code,
	}
}

/*
AgentRunnerPullRequestDefault handles this case with default header values.

error
*/
type AgentRunnerPullRequestDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the agent runner pull request default response
func (o *AgentRunnerPullRequestDefault) Code() int {
	return o._statusCode
}

func (o *AgentRunnerPullRequestDefault) Error() string {
	return fmt.Sprintf("[POST /agent_runners/{agent_runner_id}/pull_request][%d] agentRunnerPullRequest default  %+v", o._statusCode, o.Payload)
}

func (o *AgentRunnerPullRequestDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *AgentRunnerPullRequestDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
