// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewCreateSiteBuildParams creates a new CreateSiteBuildParams object
// with the default values initialized.
func NewCreateSiteBuildParams() *CreateSiteBuildParams {
	var ()
	return &CreateSiteBuildParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSiteBuildParamsWithTimeout creates a new CreateSiteBuildParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSiteBuildParamsWithTimeout(timeout time.Duration) *CreateSiteBuildParams {
	var ()
	return &CreateSiteBuildParams{

		timeout: timeout,
	}
}

// NewCreateSiteBuildParamsWithContext creates a new CreateSiteBuildParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSiteBuildParamsWithContext(ctx context.Context) *CreateSiteBuildParams {
	var ()
	return &CreateSiteBuildParams{

		Context: ctx,
	}
}

// NewCreateSiteBuildParamsWithHTTPClient creates a new CreateSiteBuildParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSiteBuildParamsWithHTTPClient(client *http.Client) *CreateSiteBuildParams {
	var ()
	return &CreateSiteBuildParams{
		HTTPClient: client,
	}
}

/*
CreateSiteBuildParams contains all the parameters to send to the API endpoint
for the create site build operation typically these are written to a http.Request
*/
type CreateSiteBuildParams struct {

	/*Branch
	  If no branch is specified, it is treated as a production deploy If a branch IS specified and matches the main branch, it is also production If a branch is specified and doesn't match the main branch, it is a branch deploy

	*/
	Branch *string
	/*ClearCache
	  Whether to clear the build cache before building

	*/
	ClearCache *bool
	/*Image
	  The build image tag to use for the build

	*/
	Image *string
	/*SiteID*/
	SiteID string
	/*TemplateID
	  The build template to use for the build

	*/
	TemplateID *string
	/*Title
	  The title of the build

	*/
	Title *string
	/*Zip
	  A zip file containing the site files to build.
	Only used with Content-Type 'multipart/form-data'.
	Alternatively, set Content-Type to 'application/zip' and send the zip as the raw request body (no 'zip' parameter needed).


	*/
	Zip runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create site build params
func (o *CreateSiteBuildParams) WithTimeout(timeout time.Duration) *CreateSiteBuildParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create site build params
func (o *CreateSiteBuildParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create site build params
func (o *CreateSiteBuildParams) WithContext(ctx context.Context) *CreateSiteBuildParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create site build params
func (o *CreateSiteBuildParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create site build params
func (o *CreateSiteBuildParams) WithHTTPClient(client *http.Client) *CreateSiteBuildParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create site build params
func (o *CreateSiteBuildParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranch adds the branch to the create site build params
func (o *CreateSiteBuildParams) WithBranch(branch *string) *CreateSiteBuildParams {
	o.SetBranch(branch)
	return o
}

// SetBranch adds the branch to the create site build params
func (o *CreateSiteBuildParams) SetBranch(branch *string) {
	o.Branch = branch
}

// WithClearCache adds the clearCache to the create site build params
func (o *CreateSiteBuildParams) WithClearCache(clearCache *bool) *CreateSiteBuildParams {
	o.SetClearCache(clearCache)
	return o
}

// SetClearCache adds the clearCache to the create site build params
func (o *CreateSiteBuildParams) SetClearCache(clearCache *bool) {
	o.ClearCache = clearCache
}

// WithImage adds the image to the create site build params
func (o *CreateSiteBuildParams) WithImage(image *string) *CreateSiteBuildParams {
	o.SetImage(image)
	return o
}

// SetImage adds the image to the create site build params
func (o *CreateSiteBuildParams) SetImage(image *string) {
	o.Image = image
}

// WithSiteID adds the siteID to the create site build params
func (o *CreateSiteBuildParams) WithSiteID(siteID string) *CreateSiteBuildParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the create site build params
func (o *CreateSiteBuildParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WithTemplateID adds the templateID to the create site build params
func (o *CreateSiteBuildParams) WithTemplateID(templateID *string) *CreateSiteBuildParams {
	o.SetTemplateID(templateID)
	return o
}

// SetTemplateID adds the templateId to the create site build params
func (o *CreateSiteBuildParams) SetTemplateID(templateID *string) {
	o.TemplateID = templateID
}

// WithTitle adds the title to the create site build params
func (o *CreateSiteBuildParams) WithTitle(title *string) *CreateSiteBuildParams {
	o.SetTitle(title)
	return o
}

// SetTitle adds the title to the create site build params
func (o *CreateSiteBuildParams) SetTitle(title *string) {
	o.Title = title
}

// WithZip adds the zip to the create site build params
func (o *CreateSiteBuildParams) WithZip(zip runtime.NamedReadCloser) *CreateSiteBuildParams {
	o.SetZip(zip)
	return o
}

// SetZip adds the zip to the create site build params
func (o *CreateSiteBuildParams) SetZip(zip runtime.NamedReadCloser) {
	o.Zip = zip
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSiteBuildParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Branch != nil {

		// query param branch
		var qrBranch string
		if o.Branch != nil {
			qrBranch = *o.Branch
		}
		qBranch := qrBranch
		if qBranch != "" {
			if err := r.SetQueryParam("branch", qBranch); err != nil {
				return err
			}
		}

	}

	if o.ClearCache != nil {

		// query param clear_cache
		var qrClearCache bool
		if o.ClearCache != nil {
			qrClearCache = *o.ClearCache
		}
		qClearCache := swag.FormatBool(qrClearCache)
		if qClearCache != "" {
			if err := r.SetQueryParam("clear_cache", qClearCache); err != nil {
				return err
			}
		}

	}

	if o.Image != nil {

		// query param image
		var qrImage string
		if o.Image != nil {
			qrImage = *o.Image
		}
		qImage := qrImage
		if qImage != "" {
			if err := r.SetQueryParam("image", qImage); err != nil {
				return err
			}
		}

	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if o.TemplateID != nil {

		// query param template_id
		var qrTemplateID string
		if o.TemplateID != nil {
			qrTemplateID = *o.TemplateID
		}
		qTemplateID := qrTemplateID
		if qTemplateID != "" {
			if err := r.SetQueryParam("template_id", qTemplateID); err != nil {
				return err
			}
		}

	}

	if o.Title != nil {

		// query param title
		var qrTitle string
		if o.Title != nil {
			qrTitle = *o.Title
		}
		qTitle := qrTitle
		if qTitle != "" {
			if err := r.SetQueryParam("title", qTitle); err != nil {
				return err
			}
		}

	}

	if o.Zip != nil {

		if o.Zip != nil {

			// form file param zip
			if err := r.SetFileParam("zip", o.Zip); err != nil {
				return err
			}

		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
