// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// CreateSiteDatabaseSnapshotReader is a Reader for the CreateSiteDatabaseSnapshot structure.
type CreateSiteDatabaseSnapshotReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSiteDatabaseSnapshotReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateSiteDatabaseSnapshotCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateSiteDatabaseSnapshotDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateSiteDatabaseSnapshotCreated creates a CreateSiteDatabaseSnapshotCreated with default headers values
func NewCreateSiteDatabaseSnapshotCreated() *CreateSiteDatabaseSnapshotCreated {
	return &CreateSiteDatabaseSnapshotCreated{}
}

/*
CreateSiteDatabaseSnapshotCreated handles this case with default header values.

Created
*/
type CreateSiteDatabaseSnapshotCreated struct {
	Payload *models.DatabaseSnapshot
}

func (o *CreateSiteDatabaseSnapshotCreated) Error() string {
	return fmt.Sprintf("[POST /sites/{site_id}/database/snapshot][%d] createSiteDatabaseSnapshotCreated  %+v", 201, o.Payload)
}

func (o *CreateSiteDatabaseSnapshotCreated) GetPayload() *models.DatabaseSnapshot {
	return o.Payload
}

func (o *CreateSiteDatabaseSnapshotCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DatabaseSnapshot)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSiteDatabaseSnapshotDefault creates a CreateSiteDatabaseSnapshotDefault with default headers values
func NewCreateSiteDatabaseSnapshotDefault(code int) *CreateSiteDatabaseSnapshotDefault {
	return &CreateSiteDatabaseSnapshotDefault{
		_statusCode: code,
	}
}

/*
CreateSiteDatabaseSnapshotDefault handles this case with default header values.

error
*/
type CreateSiteDatabaseSnapshotDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create site database snapshot default response
func (o *CreateSiteDatabaseSnapshotDefault) Code() int {
	return o._statusCode
}

func (o *CreateSiteDatabaseSnapshotDefault) Error() string {
	return fmt.Sprintf("[POST /sites/{site_id}/database/snapshot][%d] createSiteDatabaseSnapshot default  %+v", o._statusCode, o.Payload)
}

func (o *CreateSiteDatabaseSnapshotDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateSiteDatabaseSnapshotDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
