// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// CreateEnvVarsReader is a Reader for the CreateEnvVars structure.
type CreateEnvVarsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateEnvVarsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateEnvVarsCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewCreateEnvVarsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCreateEnvVarsCreated creates a CreateEnvVarsCreated with default headers values
func NewCreateEnvVarsCreated() *CreateEnvVarsCreated {
	return &CreateEnvVarsCreated{}
}

/*CreateEnvVarsCreated handles this case with default header values.

OK
*/
type CreateEnvVarsCreated struct {
	Payload []*models.EnvVar
}

func (o *CreateEnvVarsCreated) Error() string {
	return fmt.Sprintf("[POST /accounts/{account_id}/env][%d] createEnvVarsCreated  %+v", 201, o.Payload)
}

func (o *CreateEnvVarsCreated) GetPayload() []*models.EnvVar {
	return o.Payload
}

func (o *CreateEnvVarsCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateEnvVarsDefault creates a CreateEnvVarsDefault with default headers values
func NewCreateEnvVarsDefault(code int) *CreateEnvVarsDefault {
	return &CreateEnvVarsDefault{
		_statusCode: code,
	}
}

/*CreateEnvVarsDefault handles this case with default header values.

error
*/
type CreateEnvVarsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the create env vars default response
func (o *CreateEnvVarsDefault) Code() int {
	return o._statusCode
}

func (o *CreateEnvVarsDefault) Error() string {
	return fmt.Sprintf("[POST /accounts/{account_id}/env][%d] createEnvVars default  %+v", o._statusCode, o.Payload)
}

func (o *CreateEnvVarsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *CreateEnvVarsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
