// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSiteFormParams creates a new DeleteSiteFormParams object
// with the default values initialized.
func NewDeleteSiteFormParams() *DeleteSiteFormParams {
	var ()
	return &DeleteSiteFormParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSiteFormParamsWithTimeout creates a new DeleteSiteFormParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSiteFormParamsWithTimeout(timeout time.Duration) *DeleteSiteFormParams {
	var ()
	return &DeleteSiteFormParams{

		timeout: timeout,
	}
}

// NewDeleteSiteFormParamsWithContext creates a new DeleteSiteFormParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSiteFormParamsWithContext(ctx context.Context) *DeleteSiteFormParams {
	var ()
	return &DeleteSiteFormParams{

		Context: ctx,
	}
}

// NewDeleteSiteFormParamsWithHTTPClient creates a new DeleteSiteFormParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSiteFormParamsWithHTTPClient(client *http.Client) *DeleteSiteFormParams {
	var ()
	return &DeleteSiteFormParams{
		HTTPClient: client,
	}
}

/*DeleteSiteFormParams contains all the parameters to send to the API endpoint
for the delete site form operation typically these are written to a http.Request
*/
type DeleteSiteFormParams struct {

	/*FormID*/
	FormID string
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete site form params
func (o *DeleteSiteFormParams) WithTimeout(timeout time.Duration) *DeleteSiteFormParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete site form params
func (o *DeleteSiteFormParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete site form params
func (o *DeleteSiteFormParams) WithContext(ctx context.Context) *DeleteSiteFormParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete site form params
func (o *DeleteSiteFormParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete site form params
func (o *DeleteSiteFormParams) WithHTTPClient(client *http.Client) *DeleteSiteFormParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete site form params
func (o *DeleteSiteFormParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFormID adds the formID to the delete site form params
func (o *DeleteSiteFormParams) WithFormID(formID string) *DeleteSiteFormParams {
	o.SetFormID(formID)
	return o
}

// SetFormID adds the formId to the delete site form params
func (o *DeleteSiteFormParams) SetFormID(formID string) {
	o.FormID = formID
}

// WithSiteID adds the siteID to the delete site form params
func (o *DeleteSiteFormParams) WithSiteID(siteID string) *DeleteSiteFormParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the delete site form params
func (o *DeleteSiteFormParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSiteFormParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param form_id
	if err := r.SetPathParam("form_id", o.FormID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
