// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// DeleteSiteDatabaseBranchReader is a Reader for the DeleteSiteDatabaseBranch structure.
type DeleteSiteDatabaseBranchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteSiteDatabaseBranchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteSiteDatabaseBranchNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDeleteSiteDatabaseBranchDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteSiteDatabaseBranchNoContent creates a DeleteSiteDatabaseBranchNoContent with default headers values
func NewDeleteSiteDatabaseBranchNoContent() *DeleteSiteDatabaseBranchNoContent {
	return &DeleteSiteDatabaseBranchNoContent{}
}

/*
DeleteSiteDatabaseBranchNoContent handles this case with default header values.

Deleted
*/
type DeleteSiteDatabaseBranchNoContent struct {
}

func (o *DeleteSiteDatabaseBranchNoContent) Error() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/database/branch/{deploy_id}][%d] deleteSiteDatabaseBranchNoContent ", 204)
}

func (o *DeleteSiteDatabaseBranchNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteSiteDatabaseBranchDefault creates a DeleteSiteDatabaseBranchDefault with default headers values
func NewDeleteSiteDatabaseBranchDefault(code int) *DeleteSiteDatabaseBranchDefault {
	return &DeleteSiteDatabaseBranchDefault{
		_statusCode: code,
	}
}

/*
DeleteSiteDatabaseBranchDefault handles this case with default header values.

error
*/
type DeleteSiteDatabaseBranchDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the delete site database branch default response
func (o *DeleteSiteDatabaseBranchDefault) Code() int {
	return o._statusCode
}

func (o *DeleteSiteDatabaseBranchDefault) Error() string {
	return fmt.Sprintf("[DELETE /sites/{site_id}/database/branch/{deploy_id}][%d] deleteSiteDatabaseBranch default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteSiteDatabaseBranchDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DeleteSiteDatabaseBranchDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
