// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteSiteParams creates a new DeleteSiteParams object
// with the default values initialized.
func NewDeleteSiteParams() *DeleteSiteParams {
	var ()
	return &DeleteSiteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteSiteParamsWithTimeout creates a new DeleteSiteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteSiteParamsWithTimeout(timeout time.Duration) *DeleteSiteParams {
	var ()
	return &DeleteSiteParams{

		timeout: timeout,
	}
}

// NewDeleteSiteParamsWithContext creates a new DeleteSiteParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteSiteParamsWithContext(ctx context.Context) *DeleteSiteParams {
	var ()
	return &DeleteSiteParams{

		Context: ctx,
	}
}

// NewDeleteSiteParamsWithHTTPClient creates a new DeleteSiteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteSiteParamsWithHTTPClient(client *http.Client) *DeleteSiteParams {
	var ()
	return &DeleteSiteParams{
		HTTPClient: client,
	}
}

/*DeleteSiteParams contains all the parameters to send to the API endpoint
for the delete site operation typically these are written to a http.Request
*/
type DeleteSiteParams struct {

	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete site params
func (o *DeleteSiteParams) WithTimeout(timeout time.Duration) *DeleteSiteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete site params
func (o *DeleteSiteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete site params
func (o *DeleteSiteParams) WithContext(ctx context.Context) *DeleteSiteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete site params
func (o *DeleteSiteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete site params
func (o *DeleteSiteParams) WithHTTPClient(client *http.Client) *DeleteSiteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete site params
func (o *DeleteSiteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSiteID adds the siteID to the delete site params
func (o *DeleteSiteParams) WithSiteID(siteID string) *DeleteSiteParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the delete site params
func (o *DeleteSiteParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSiteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
