// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteHookReader is a Reader for the DeleteHook structure.
type DeleteHookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteHookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteHookNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteHookNoContent creates a DeleteHookNoContent with default headers values
func NewDeleteHookNoContent() *DeleteHookNoContent {
	return &DeleteHookNoContent{}
}

/*DeleteHookNoContent handles this case with default header values.

No content
*/
type DeleteHookNoContent struct {
}

func (o *DeleteHookNoContent) Error() string {
	return fmt.Sprintf("[DELETE /hooks/{hook_id}][%d] deleteHookNoContent ", 204)
}

func (o *DeleteHookNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
