// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// DisableSiteReader is a Reader for the DisableSite structure.
type DisableSiteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DisableSiteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDisableSiteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDisableSiteDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDisableSiteNoContent creates a DisableSiteNoContent with default headers values
func NewDisableSiteNoContent() *DisableSiteNoContent {
	return &DisableSiteNoContent{}
}

/*
DisableSiteNoContent handles this case with default header values.

No content
*/
type DisableSiteNoContent struct {
}

func (o *DisableSiteNoContent) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/disable][%d] disableSiteNoContent ", 204)
}

func (o *DisableSiteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDisableSiteDefault creates a DisableSiteDefault with default headers values
func NewDisableSiteDefault(code int) *DisableSiteDefault {
	return &DisableSiteDefault{
		_statusCode: code,
	}
}

/*
DisableSiteDefault handles this case with default header values.

error
*/
type DisableSiteDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the disable site default response
func (o *DisableSiteDefault) Code() int {
	return o._statusCode
}

func (o *DisableSiteDefault) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/disable][%d] disableSite default  %+v", o._statusCode, o.Payload)
}

func (o *DisableSiteDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DisableSiteDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
