// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// ExchangeTicketReader is a Reader for the ExchangeTicket structure.
type ExchangeTicketReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExchangeTicketReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewExchangeTicketCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewExchangeTicketDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewExchangeTicketCreated creates a ExchangeTicketCreated with default headers values
func NewExchangeTicketCreated() *ExchangeTicketCreated {
	return &ExchangeTicketCreated{}
}

/*ExchangeTicketCreated handles this case with default header values.

ok
*/
type ExchangeTicketCreated struct {
	Payload *models.AccessToken
}

func (o *ExchangeTicketCreated) Error() string {
	return fmt.Sprintf("[POST /oauth/tickets/{ticket_id}/exchange][%d] exchangeTicketCreated  %+v", 201, o.Payload)
}

func (o *ExchangeTicketCreated) GetPayload() *models.AccessToken {
	return o.Payload
}

func (o *ExchangeTicketCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccessToken)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExchangeTicketDefault creates a ExchangeTicketDefault with default headers values
func NewExchangeTicketDefault(code int) *ExchangeTicketDefault {
	return &ExchangeTicketDefault{
		_statusCode: code,
	}
}

/*ExchangeTicketDefault handles this case with default header values.

error
*/
type ExchangeTicketDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the exchange ticket default response
func (o *ExchangeTicketDefault) Code() int {
	return o._statusCode
}

func (o *ExchangeTicketDefault) Error() string {
	return fmt.Sprintf("[POST /oauth/tickets/{ticket_id}/exchange][%d] exchangeTicket default  %+v", o._statusCode, o.Payload)
}

func (o *ExchangeTicketDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ExchangeTicketDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
