// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetHookParams creates a new GetHookParams object
// with the default values initialized.
func NewGetHookParams() *GetHookParams {
	var ()
	return &GetHookParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetHookParamsWithTimeout creates a new GetHookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetHookParamsWithTimeout(timeout time.Duration) *GetHookParams {
	var ()
	return &GetHookParams{

		timeout: timeout,
	}
}

// NewGetHookParamsWithContext creates a new GetHookParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetHookParamsWithContext(ctx context.Context) *GetHookParams {
	var ()
	return &GetHookParams{

		Context: ctx,
	}
}

// NewGetHookParamsWithHTTPClient creates a new GetHookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetHookParamsWithHTTPClient(client *http.Client) *GetHookParams {
	var ()
	return &GetHookParams{
		HTTPClient: client,
	}
}

/*GetHookParams contains all the parameters to send to the API endpoint
for the get hook operation typically these are written to a http.Request
*/
type GetHookParams struct {

	/*HookID*/
	HookID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get hook params
func (o *GetHookParams) WithTimeout(timeout time.Duration) *GetHookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get hook params
func (o *GetHookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get hook params
func (o *GetHookParams) WithContext(ctx context.Context) *GetHookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get hook params
func (o *GetHookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get hook params
func (o *GetHookParams) WithHTTPClient(client *http.Client) *GetHookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get hook params
func (o *GetHookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHookID adds the hookID to the get hook params
func (o *GetHookParams) WithHookID(hookID string) *GetHookParams {
	o.SetHookID(hookID)
	return o
}

// SetHookID adds the hookId to the get hook params
func (o *GetHookParams) SetHookID(hookID string) {
	o.HookID = hookID
}

// WriteToRequest writes these params to a swagger request
func (o *GetHookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param hook_id
	if err := r.SetPathParam("hook_id", o.HookID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
