// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAccountBuildStatusParams creates a new GetAccountBuildStatusParams object
// with the default values initialized.
func NewGetAccountBuildStatusParams() *GetAccountBuildStatusParams {
	var ()
	return &GetAccountBuildStatusParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccountBuildStatusParamsWithTimeout creates a new GetAccountBuildStatusParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccountBuildStatusParamsWithTimeout(timeout time.Duration) *GetAccountBuildStatusParams {
	var ()
	return &GetAccountBuildStatusParams{

		timeout: timeout,
	}
}

// NewGetAccountBuildStatusParamsWithContext creates a new GetAccountBuildStatusParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAccountBuildStatusParamsWithContext(ctx context.Context) *GetAccountBuildStatusParams {
	var ()
	return &GetAccountBuildStatusParams{

		Context: ctx,
	}
}

// NewGetAccountBuildStatusParamsWithHTTPClient creates a new GetAccountBuildStatusParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAccountBuildStatusParamsWithHTTPClient(client *http.Client) *GetAccountBuildStatusParams {
	var ()
	return &GetAccountBuildStatusParams{
		HTTPClient: client,
	}
}

/*GetAccountBuildStatusParams contains all the parameters to send to the API endpoint
for the get account build status operation typically these are written to a http.Request
*/
type GetAccountBuildStatusParams struct {

	/*AccountID*/
	AccountID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get account build status params
func (o *GetAccountBuildStatusParams) WithTimeout(timeout time.Duration) *GetAccountBuildStatusParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get account build status params
func (o *GetAccountBuildStatusParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get account build status params
func (o *GetAccountBuildStatusParams) WithContext(ctx context.Context) *GetAccountBuildStatusParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get account build status params
func (o *GetAccountBuildStatusParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get account build status params
func (o *GetAccountBuildStatusParams) WithHTTPClient(client *http.Client) *GetAccountBuildStatusParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get account build status params
func (o *GetAccountBuildStatusParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountID adds the accountID to the get account build status params
func (o *GetAccountBuildStatusParams) WithAccountID(accountID string) *GetAccountBuildStatusParams {
	o.SetAccountID(accountID)
	return o
}

// SetAccountID adds the accountId to the get account build status params
func (o *GetAccountBuildStatusParams) SetAccountID(accountID string) {
	o.AccountID = accountID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccountBuildStatusParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_id
	if err := r.SetPathParam("account_id", o.AccountID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
