// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// GetAccountReader is a Reader for the GetAccount structure.
type GetAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAccountOK creates a GetAccountOK with default headers values
func NewGetAccountOK() *GetAccountOK {
	return &GetAccountOK{}
}

/*GetAccountOK handles this case with default header values.

OK
*/
type GetAccountOK struct {
	Payload []*models.AccountMembership
}

func (o *GetAccountOK) Error() string {
	return fmt.Sprintf("[GET /accounts/{account_id}][%d] getAccountOK  %+v", 200, o.Payload)
}

func (o *GetAccountOK) GetPayload() []*models.AccountMembership {
	return o.Payload
}

func (o *GetAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountDefault creates a GetAccountDefault with default headers values
func NewGetAccountDefault(code int) *GetAccountDefault {
	return &GetAccountDefault{
		_statusCode: code,
	}
}

/*GetAccountDefault handles this case with default header values.

error
*/
type GetAccountDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get account default response
func (o *GetAccountDefault) Code() int {
	return o._statusCode
}

func (o *GetAccountDefault) Error() string {
	return fmt.Sprintf("[GET /accounts/{account_id}][%d] getAccount default  %+v", o._statusCode, o.Payload)
}

func (o *GetAccountDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
