// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// GetAgentRunnerReader is a Reader for the GetAgentRunner structure.
type GetAgentRunnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAgentRunnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAgentRunnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetAgentRunnerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAgentRunnerOK creates a GetAgentRunnerOK with default headers values
func NewGetAgentRunnerOK() *GetAgentRunnerOK {
	return &GetAgentRunnerOK{}
}

/*
GetAgentRunnerOK handles this case with default header values.

OK
*/
type GetAgentRunnerOK struct {
	Payload *models.AgentRunner
}

func (o *GetAgentRunnerOK) Error() string {
	return fmt.Sprintf("[GET /agent_runners/{agent_runner_id}][%d] getAgentRunnerOK  %+v", 200, o.Payload)
}

func (o *GetAgentRunnerOK) GetPayload() *models.AgentRunner {
	return o.Payload
}

func (o *GetAgentRunnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AgentRunner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAgentRunnerDefault creates a GetAgentRunnerDefault with default headers values
func NewGetAgentRunnerDefault(code int) *GetAgentRunnerDefault {
	return &GetAgentRunnerDefault{
		_statusCode: code,
	}
}

/*
GetAgentRunnerDefault handles this case with default header values.

error
*/
type GetAgentRunnerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get agent runner default response
func (o *GetAgentRunnerDefault) Code() int {
	return o._statusCode
}

func (o *GetAgentRunnerDefault) Error() string {
	return fmt.Sprintf("[GET /agent_runners/{agent_runner_id}][%d] getAgentRunner default  %+v", o._statusCode, o.Payload)
}

func (o *GetAgentRunnerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetAgentRunnerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
