// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetSiteDevServerParams creates a new GetSiteDevServerParams object
// with the default values initialized.
func NewGetSiteDevServerParams() *GetSiteDevServerParams {
	var ()
	return &GetSiteDevServerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSiteDevServerParamsWithTimeout creates a new GetSiteDevServerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSiteDevServerParamsWithTimeout(timeout time.Duration) *GetSiteDevServerParams {
	var ()
	return &GetSiteDevServerParams{

		timeout: timeout,
	}
}

// NewGetSiteDevServerParamsWithContext creates a new GetSiteDevServerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSiteDevServerParamsWithContext(ctx context.Context) *GetSiteDevServerParams {
	var ()
	return &GetSiteDevServerParams{

		Context: ctx,
	}
}

// NewGetSiteDevServerParamsWithHTTPClient creates a new GetSiteDevServerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSiteDevServerParamsWithHTTPClient(client *http.Client) *GetSiteDevServerParams {
	var ()
	return &GetSiteDevServerParams{
		HTTPClient: client,
	}
}

/*
GetSiteDevServerParams contains all the parameters to send to the API endpoint
for the get site dev server operation typically these are written to a http.Request
*/
type GetSiteDevServerParams struct {

	/*DevServerID*/
	DevServerID string
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get site dev server params
func (o *GetSiteDevServerParams) WithTimeout(timeout time.Duration) *GetSiteDevServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get site dev server params
func (o *GetSiteDevServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get site dev server params
func (o *GetSiteDevServerParams) WithContext(ctx context.Context) *GetSiteDevServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get site dev server params
func (o *GetSiteDevServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get site dev server params
func (o *GetSiteDevServerParams) WithHTTPClient(client *http.Client) *GetSiteDevServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get site dev server params
func (o *GetSiteDevServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDevServerID adds the devServerID to the get site dev server params
func (o *GetSiteDevServerParams) WithDevServerID(devServerID string) *GetSiteDevServerParams {
	o.SetDevServerID(devServerID)
	return o
}

// SetDevServerID adds the devServerId to the get site dev server params
func (o *GetSiteDevServerParams) SetDevServerID(devServerID string) {
	o.DevServerID = devServerID
}

// WithSiteID adds the siteID to the get site dev server params
func (o *GetSiteDevServerParams) WithSiteID(siteID string) *GetSiteDevServerParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the get site dev server params
func (o *GetSiteDevServerParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *GetSiteDevServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dev_server_id
	if err := r.SetPathParam("dev_server_id", o.DevServerID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
