// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetIndividualDNSRecordParams creates a new GetIndividualDNSRecordParams object
// with the default values initialized.
func NewGetIndividualDNSRecordParams() *GetIndividualDNSRecordParams {
	var ()
	return &GetIndividualDNSRecordParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetIndividualDNSRecordParamsWithTimeout creates a new GetIndividualDNSRecordParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetIndividualDNSRecordParamsWithTimeout(timeout time.Duration) *GetIndividualDNSRecordParams {
	var ()
	return &GetIndividualDNSRecordParams{

		timeout: timeout,
	}
}

// NewGetIndividualDNSRecordParamsWithContext creates a new GetIndividualDNSRecordParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetIndividualDNSRecordParamsWithContext(ctx context.Context) *GetIndividualDNSRecordParams {
	var ()
	return &GetIndividualDNSRecordParams{

		Context: ctx,
	}
}

// NewGetIndividualDNSRecordParamsWithHTTPClient creates a new GetIndividualDNSRecordParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetIndividualDNSRecordParamsWithHTTPClient(client *http.Client) *GetIndividualDNSRecordParams {
	var ()
	return &GetIndividualDNSRecordParams{
		HTTPClient: client,
	}
}

/*GetIndividualDNSRecordParams contains all the parameters to send to the API endpoint
for the get individual Dns record operation typically these are written to a http.Request
*/
type GetIndividualDNSRecordParams struct {

	/*DNSRecordID*/
	DNSRecordID string
	/*ZoneID*/
	ZoneID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) WithTimeout(timeout time.Duration) *GetIndividualDNSRecordParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) WithContext(ctx context.Context) *GetIndividualDNSRecordParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) WithHTTPClient(client *http.Client) *GetIndividualDNSRecordParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDNSRecordID adds the dNSRecordID to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) WithDNSRecordID(dNSRecordID string) *GetIndividualDNSRecordParams {
	o.SetDNSRecordID(dNSRecordID)
	return o
}

// SetDNSRecordID adds the dnsRecordId to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) SetDNSRecordID(dNSRecordID string) {
	o.DNSRecordID = dNSRecordID
}

// WithZoneID adds the zoneID to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) WithZoneID(zoneID string) *GetIndividualDNSRecordParams {
	o.SetZoneID(zoneID)
	return o
}

// SetZoneID adds the zoneId to the get individual Dns record params
func (o *GetIndividualDNSRecordParams) SetZoneID(zoneID string) {
	o.ZoneID = zoneID
}

// WriteToRequest writes these params to a swagger request
func (o *GetIndividualDNSRecordParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param dns_record_id
	if err := r.SetPathParam("dns_record_id", o.DNSRecordID); err != nil {
		return err
	}

	// path param zone_id
	if err := r.SetPathParam("zone_id", o.ZoneID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
