// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAgentRunnerParams creates a new GetAgentRunnerParams object
// with the default values initialized.
func NewGetAgentRunnerParams() *GetAgentRunnerParams {
	var ()
	return &GetAgentRunnerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAgentRunnerParamsWithTimeout creates a new GetAgentRunnerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAgentRunnerParamsWithTimeout(timeout time.Duration) *GetAgentRunnerParams {
	var ()
	return &GetAgentRunnerParams{

		timeout: timeout,
	}
}

// NewGetAgentRunnerParamsWithContext creates a new GetAgentRunnerParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAgentRunnerParamsWithContext(ctx context.Context) *GetAgentRunnerParams {
	var ()
	return &GetAgentRunnerParams{

		Context: ctx,
	}
}

// NewGetAgentRunnerParamsWithHTTPClient creates a new GetAgentRunnerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAgentRunnerParamsWithHTTPClient(client *http.Client) *GetAgentRunnerParams {
	var ()
	return &GetAgentRunnerParams{
		HTTPClient: client,
	}
}

/*
GetAgentRunnerParams contains all the parameters to send to the API endpoint
for the get agent runner operation typically these are written to a http.Request
*/
type GetAgentRunnerParams struct {

	/*AgentRunnerID*/
	AgentRunnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get agent runner params
func (o *GetAgentRunnerParams) WithTimeout(timeout time.Duration) *GetAgentRunnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get agent runner params
func (o *GetAgentRunnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get agent runner params
func (o *GetAgentRunnerParams) WithContext(ctx context.Context) *GetAgentRunnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get agent runner params
func (o *GetAgentRunnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get agent runner params
func (o *GetAgentRunnerParams) WithHTTPClient(client *http.Client) *GetAgentRunnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get agent runner params
func (o *GetAgentRunnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentRunnerID adds the agentRunnerID to the get agent runner params
func (o *GetAgentRunnerParams) WithAgentRunnerID(agentRunnerID string) *GetAgentRunnerParams {
	o.SetAgentRunnerID(agentRunnerID)
	return o
}

// SetAgentRunnerID adds the agentRunnerId to the get agent runner params
func (o *GetAgentRunnerParams) SetAgentRunnerID(agentRunnerID string) {
	o.AgentRunnerID = agentRunnerID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAgentRunnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent_runner_id
	if err := r.SetPathParam("agent_runner_id", o.AgentRunnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
