// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// ListSiteDevServersReader is a Reader for the ListSiteDevServers structure.
type ListSiteDevServersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSiteDevServersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSiteDevServersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListSiteDevServersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListSiteDevServersOK creates a ListSiteDevServersOK with default headers values
func NewListSiteDevServersOK() *ListSiteDevServersOK {
	return &ListSiteDevServersOK{}
}

/*
ListSiteDevServersOK handles this case with default header values.

OK
*/
type ListSiteDevServersOK struct {
	Payload []*models.DevServer
}

func (o *ListSiteDevServersOK) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/dev_servers][%d] listSiteDevServersOK  %+v", 200, o.Payload)
}

func (o *ListSiteDevServersOK) GetPayload() []*models.DevServer {
	return o.Payload
}

func (o *ListSiteDevServersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSiteDevServersDefault creates a ListSiteDevServersDefault with default headers values
func NewListSiteDevServersDefault(code int) *ListSiteDevServersDefault {
	return &ListSiteDevServersDefault{
		_statusCode: code,
	}
}

/*
ListSiteDevServersDefault handles this case with default header values.

error
*/
type ListSiteDevServersDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list site dev servers default response
func (o *ListSiteDevServersDefault) Code() int {
	return o._statusCode
}

func (o *ListSiteDevServersDefault) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/dev_servers][%d] listSiteDevServers default  %+v", o._statusCode, o.Payload)
}

func (o *ListSiteDevServersDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListSiteDevServersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
