package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListFormSubmissionsParams creates a new ListFormSubmissionsParams object
// with the default values initialized.
func NewListFormSubmissionsParams() *ListFormSubmissionsParams {
	var ()
	return &ListFormSubmissionsParams{}
}

/*ListFormSubmissionsParams contains all the parameters to send to the API endpoint
for the list form submissions operation typically these are written to a http.Request
*/
type ListFormSubmissionsParams struct {

	/*FormID*/
	FormID string
}

// WithFormID adds the formId to the list form submissions params
func (o *ListFormSubmissionsParams) WithFormID(FormID string) *ListFormSubmissionsParams {
	o.FormID = FormID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListFormSubmissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param form_id
	if err := r.SetPathParam("form_id", o.FormID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
