// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListPaymentMethodsForUserParams creates a new ListPaymentMethodsForUserParams object
// with the default values initialized.
func NewListPaymentMethodsForUserParams() *ListPaymentMethodsForUserParams {

	return &ListPaymentMethodsForUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListPaymentMethodsForUserParamsWithTimeout creates a new ListPaymentMethodsForUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListPaymentMethodsForUserParamsWithTimeout(timeout time.Duration) *ListPaymentMethodsForUserParams {

	return &ListPaymentMethodsForUserParams{

		timeout: timeout,
	}
}

// NewListPaymentMethodsForUserParamsWithContext creates a new ListPaymentMethodsForUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewListPaymentMethodsForUserParamsWithContext(ctx context.Context) *ListPaymentMethodsForUserParams {

	return &ListPaymentMethodsForUserParams{

		Context: ctx,
	}
}

// NewListPaymentMethodsForUserParamsWithHTTPClient creates a new ListPaymentMethodsForUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListPaymentMethodsForUserParamsWithHTTPClient(client *http.Client) *ListPaymentMethodsForUserParams {

	return &ListPaymentMethodsForUserParams{
		HTTPClient: client,
	}
}

/*ListPaymentMethodsForUserParams contains all the parameters to send to the API endpoint
for the list payment methods for user operation typically these are written to a http.Request
*/
type ListPaymentMethodsForUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list payment methods for user params
func (o *ListPaymentMethodsForUserParams) WithTimeout(timeout time.Duration) *ListPaymentMethodsForUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list payment methods for user params
func (o *ListPaymentMethodsForUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list payment methods for user params
func (o *ListPaymentMethodsForUserParams) WithContext(ctx context.Context) *ListPaymentMethodsForUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list payment methods for user params
func (o *ListPaymentMethodsForUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list payment methods for user params
func (o *ListPaymentMethodsForUserParams) WithHTTPClient(client *http.Client) *ListPaymentMethodsForUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list payment methods for user params
func (o *ListPaymentMethodsForUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListPaymentMethodsForUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
