// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListAccountTypesForUserParams creates a new ListAccountTypesForUserParams object
// with the default values initialized.
func NewListAccountTypesForUserParams() *ListAccountTypesForUserParams {

	return &ListAccountTypesForUserParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListAccountTypesForUserParamsWithTimeout creates a new ListAccountTypesForUserParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListAccountTypesForUserParamsWithTimeout(timeout time.Duration) *ListAccountTypesForUserParams {

	return &ListAccountTypesForUserParams{

		timeout: timeout,
	}
}

// NewListAccountTypesForUserParamsWithContext creates a new ListAccountTypesForUserParams object
// with the default values initialized, and the ability to set a context for a request
func NewListAccountTypesForUserParamsWithContext(ctx context.Context) *ListAccountTypesForUserParams {

	return &ListAccountTypesForUserParams{

		Context: ctx,
	}
}

// NewListAccountTypesForUserParamsWithHTTPClient creates a new ListAccountTypesForUserParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListAccountTypesForUserParamsWithHTTPClient(client *http.Client) *ListAccountTypesForUserParams {

	return &ListAccountTypesForUserParams{
		HTTPClient: client,
	}
}

/*ListAccountTypesForUserParams contains all the parameters to send to the API endpoint
for the list account types for user operation typically these are written to a http.Request
*/
type ListAccountTypesForUserParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list account types for user params
func (o *ListAccountTypesForUserParams) WithTimeout(timeout time.Duration) *ListAccountTypesForUserParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list account types for user params
func (o *ListAccountTypesForUserParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list account types for user params
func (o *ListAccountTypesForUserParams) WithContext(ctx context.Context) *ListAccountTypesForUserParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list account types for user params
func (o *ListAccountTypesForUserParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list account types for user params
func (o *ListAccountTypesForUserParams) WithHTTPClient(client *http.Client) *ListAccountTypesForUserParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list account types for user params
func (o *ListAccountTypesForUserParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListAccountTypesForUserParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
