// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// ListSiteDatabaseSnapshotsReader is a Reader for the ListSiteDatabaseSnapshots structure.
type ListSiteDatabaseSnapshotsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSiteDatabaseSnapshotsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSiteDatabaseSnapshotsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListSiteDatabaseSnapshotsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListSiteDatabaseSnapshotsOK creates a ListSiteDatabaseSnapshotsOK with default headers values
func NewListSiteDatabaseSnapshotsOK() *ListSiteDatabaseSnapshotsOK {
	return &ListSiteDatabaseSnapshotsOK{}
}

/*
ListSiteDatabaseSnapshotsOK handles this case with default header values.

OK
*/
type ListSiteDatabaseSnapshotsOK struct {
	Payload *models.DatabaseSnapshotsResponse
}

func (o *ListSiteDatabaseSnapshotsOK) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/database/snapshots][%d] listSiteDatabaseSnapshotsOK  %+v", 200, o.Payload)
}

func (o *ListSiteDatabaseSnapshotsOK) GetPayload() *models.DatabaseSnapshotsResponse {
	return o.Payload
}

func (o *ListSiteDatabaseSnapshotsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DatabaseSnapshotsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSiteDatabaseSnapshotsDefault creates a ListSiteDatabaseSnapshotsDefault with default headers values
func NewListSiteDatabaseSnapshotsDefault(code int) *ListSiteDatabaseSnapshotsDefault {
	return &ListSiteDatabaseSnapshotsDefault{
		_statusCode: code,
	}
}

/*
ListSiteDatabaseSnapshotsDefault handles this case with default header values.

error
*/
type ListSiteDatabaseSnapshotsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list site database snapshots default response
func (o *ListSiteDatabaseSnapshotsDefault) Code() int {
	return o._statusCode
}

func (o *ListSiteDatabaseSnapshotsDefault) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/database/snapshots][%d] listSiteDatabaseSnapshots default  %+v", o._statusCode, o.Payload)
}

func (o *ListSiteDatabaseSnapshotsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListSiteDatabaseSnapshotsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
