// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListServiceInstancesForSiteParams creates a new ListServiceInstancesForSiteParams object
// with the default values initialized.
func NewListServiceInstancesForSiteParams() *ListServiceInstancesForSiteParams {
	var ()
	return &ListServiceInstancesForSiteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListServiceInstancesForSiteParamsWithTimeout creates a new ListServiceInstancesForSiteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListServiceInstancesForSiteParamsWithTimeout(timeout time.Duration) *ListServiceInstancesForSiteParams {
	var ()
	return &ListServiceInstancesForSiteParams{

		timeout: timeout,
	}
}

// NewListServiceInstancesForSiteParamsWithContext creates a new ListServiceInstancesForSiteParams object
// with the default values initialized, and the ability to set a context for a request
func NewListServiceInstancesForSiteParamsWithContext(ctx context.Context) *ListServiceInstancesForSiteParams {
	var ()
	return &ListServiceInstancesForSiteParams{

		Context: ctx,
	}
}

// NewListServiceInstancesForSiteParamsWithHTTPClient creates a new ListServiceInstancesForSiteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListServiceInstancesForSiteParamsWithHTTPClient(client *http.Client) *ListServiceInstancesForSiteParams {
	var ()
	return &ListServiceInstancesForSiteParams{
		HTTPClient: client,
	}
}

/*ListServiceInstancesForSiteParams contains all the parameters to send to the API endpoint
for the list service instances for site operation typically these are written to a http.Request
*/
type ListServiceInstancesForSiteParams struct {

	/*Page*/
	Page *int32
	/*PerPage*/
	PerPage *int32
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) WithTimeout(timeout time.Duration) *ListServiceInstancesForSiteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) WithContext(ctx context.Context) *ListServiceInstancesForSiteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) WithHTTPClient(client *http.Client) *ListServiceInstancesForSiteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) WithPage(page *int32) *ListServiceInstancesForSiteParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) SetPage(page *int32) {
	o.Page = page
}

// WithPerPage adds the perPage to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) WithPerPage(perPage *int32) *ListServiceInstancesForSiteParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) SetPerPage(perPage *int32) {
	o.PerPage = perPage
}

// WithSiteID adds the siteID to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) WithSiteID(siteID string) *ListServiceInstancesForSiteParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the list service instances for site params
func (o *ListServiceInstancesForSiteParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *ListServiceInstancesForSiteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int32
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt32(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}

	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
