// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// ListSiteSnippetsReader is a Reader for the ListSiteSnippets structure.
type ListSiteSnippetsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListSiteSnippetsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListSiteSnippetsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListSiteSnippetsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListSiteSnippetsOK creates a ListSiteSnippetsOK with default headers values
func NewListSiteSnippetsOK() *ListSiteSnippetsOK {
	return &ListSiteSnippetsOK{}
}

/*ListSiteSnippetsOK handles this case with default header values.

OK
*/
type ListSiteSnippetsOK struct {
	Payload []*models.Snippet
}

func (o *ListSiteSnippetsOK) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/snippets][%d] listSiteSnippetsOK  %+v", 200, o.Payload)
}

func (o *ListSiteSnippetsOK) GetPayload() []*models.Snippet {
	return o.Payload
}

func (o *ListSiteSnippetsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListSiteSnippetsDefault creates a ListSiteSnippetsDefault with default headers values
func NewListSiteSnippetsDefault(code int) *ListSiteSnippetsDefault {
	return &ListSiteSnippetsDefault{
		_statusCode: code,
	}
}

/*ListSiteSnippetsDefault handles this case with default header values.

error
*/
type ListSiteSnippetsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the list site snippets default response
func (o *ListSiteSnippetsDefault) Code() int {
	return o._statusCode
}

func (o *ListSiteSnippetsDefault) Error() string {
	return fmt.Sprintf("[GET /sites/{site_id}/snippets][%d] listSiteSnippets default  %+v", o._statusCode, o.Payload)
}

func (o *ListSiteSnippetsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListSiteSnippetsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
