// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListFormSubmissionsParams creates a new ListFormSubmissionsParams object
// with the default values initialized.
func NewListFormSubmissionsParams() *ListFormSubmissionsParams {
	var ()
	return &ListFormSubmissionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListFormSubmissionsParamsWithTimeout creates a new ListFormSubmissionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListFormSubmissionsParamsWithTimeout(timeout time.Duration) *ListFormSubmissionsParams {
	var ()
	return &ListFormSubmissionsParams{

		timeout: timeout,
	}
}

// NewListFormSubmissionsParamsWithContext creates a new ListFormSubmissionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListFormSubmissionsParamsWithContext(ctx context.Context) *ListFormSubmissionsParams {
	var ()
	return &ListFormSubmissionsParams{

		Context: ctx,
	}
}

// NewListFormSubmissionsParamsWithHTTPClient creates a new ListFormSubmissionsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListFormSubmissionsParamsWithHTTPClient(client *http.Client) *ListFormSubmissionsParams {
	var ()
	return &ListFormSubmissionsParams{
		HTTPClient: client,
	}
}

/*ListFormSubmissionsParams contains all the parameters to send to the API endpoint
for the list form submissions operation typically these are written to a http.Request
*/
type ListFormSubmissionsParams struct {

	/*FormID*/
	FormID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list form submissions params
func (o *ListFormSubmissionsParams) WithTimeout(timeout time.Duration) *ListFormSubmissionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list form submissions params
func (o *ListFormSubmissionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list form submissions params
func (o *ListFormSubmissionsParams) WithContext(ctx context.Context) *ListFormSubmissionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list form submissions params
func (o *ListFormSubmissionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list form submissions params
func (o *ListFormSubmissionsParams) WithHTTPClient(client *http.Client) *ListFormSubmissionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list form submissions params
func (o *ListFormSubmissionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFormID adds the formID to the list form submissions params
func (o *ListFormSubmissionsParams) WithFormID(formID string) *ListFormSubmissionsParams {
	o.SetFormID(formID)
	return o
}

// SetFormID adds the formId to the list form submissions params
func (o *ListFormSubmissionsParams) SetFormID(formID string) {
	o.FormID = formID
}

// WriteToRequest writes these params to a swagger request
func (o *ListFormSubmissionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param form_id
	if err := r.SetPathParam("form_id", o.FormID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
