// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListFormSubmissionParams creates a new ListFormSubmissionParams object
// with the default values initialized.
func NewListFormSubmissionParams() *ListFormSubmissionParams {
	var ()
	return &ListFormSubmissionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListFormSubmissionParamsWithTimeout creates a new ListFormSubmissionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListFormSubmissionParamsWithTimeout(timeout time.Duration) *ListFormSubmissionParams {
	var ()
	return &ListFormSubmissionParams{

		timeout: timeout,
	}
}

// NewListFormSubmissionParamsWithContext creates a new ListFormSubmissionParams object
// with the default values initialized, and the ability to set a context for a request
func NewListFormSubmissionParamsWithContext(ctx context.Context) *ListFormSubmissionParams {
	var ()
	return &ListFormSubmissionParams{

		Context: ctx,
	}
}

// NewListFormSubmissionParamsWithHTTPClient creates a new ListFormSubmissionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListFormSubmissionParamsWithHTTPClient(client *http.Client) *ListFormSubmissionParams {
	var ()
	return &ListFormSubmissionParams{
		HTTPClient: client,
	}
}

/*ListFormSubmissionParams contains all the parameters to send to the API endpoint
for the list form submission operation typically these are written to a http.Request
*/
type ListFormSubmissionParams struct {

	/*Page*/
	Page *int32
	/*PerPage*/
	PerPage *int32
	/*Query*/
	Query *string
	/*SubmissionID*/
	SubmissionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list form submission params
func (o *ListFormSubmissionParams) WithTimeout(timeout time.Duration) *ListFormSubmissionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list form submission params
func (o *ListFormSubmissionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list form submission params
func (o *ListFormSubmissionParams) WithContext(ctx context.Context) *ListFormSubmissionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list form submission params
func (o *ListFormSubmissionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list form submission params
func (o *ListFormSubmissionParams) WithHTTPClient(client *http.Client) *ListFormSubmissionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list form submission params
func (o *ListFormSubmissionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPage adds the page to the list form submission params
func (o *ListFormSubmissionParams) WithPage(page *int32) *ListFormSubmissionParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the list form submission params
func (o *ListFormSubmissionParams) SetPage(page *int32) {
	o.Page = page
}

// WithPerPage adds the perPage to the list form submission params
func (o *ListFormSubmissionParams) WithPerPage(perPage *int32) *ListFormSubmissionParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the list form submission params
func (o *ListFormSubmissionParams) SetPerPage(perPage *int32) {
	o.PerPage = perPage
}

// WithQuery adds the query to the list form submission params
func (o *ListFormSubmissionParams) WithQuery(query *string) *ListFormSubmissionParams {
	o.SetQuery(query)
	return o
}

// SetQuery adds the query to the list form submission params
func (o *ListFormSubmissionParams) SetQuery(query *string) {
	o.Query = query
}

// WithSubmissionID adds the submissionID to the list form submission params
func (o *ListFormSubmissionParams) WithSubmissionID(submissionID string) *ListFormSubmissionParams {
	o.SetSubmissionID(submissionID)
	return o
}

// SetSubmissionID adds the submissionId to the list form submission params
func (o *ListFormSubmissionParams) SetSubmissionID(submissionID string) {
	o.SubmissionID = submissionID
}

// WriteToRequest writes these params to a swagger request
func (o *ListFormSubmissionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Page != nil {

		// query param page
		var qrPage int32
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt32(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int32
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt32(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.Query != nil {

		// query param query
		var qrQuery string
		if o.Query != nil {
			qrQuery = *o.Query
		}
		qQuery := qrQuery
		if qQuery != "" {
			if err := r.SetQueryParam("query", qQuery); err != nil {
				return err
			}
		}

	}

	// path param submission_id
	if err := r.SetPathParam("submission_id", o.SubmissionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
