// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// NotifyBuildStartReader is a Reader for the NotifyBuildStart structure.
type NotifyBuildStartReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NotifyBuildStartReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewNotifyBuildStartNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewNotifyBuildStartDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewNotifyBuildStartNoContent creates a NotifyBuildStartNoContent with default headers values
func NewNotifyBuildStartNoContent() *NotifyBuildStartNoContent {
	return &NotifyBuildStartNoContent{}
}

/*NotifyBuildStartNoContent handles this case with default header values.

No content
*/
type NotifyBuildStartNoContent struct {
}

func (o *NotifyBuildStartNoContent) Error() string {
	return fmt.Sprintf("[POST /builds/{build_id}/start][%d] notifyBuildStartNoContent ", 204)
}

func (o *NotifyBuildStartNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewNotifyBuildStartDefault creates a NotifyBuildStartDefault with default headers values
func NewNotifyBuildStartDefault(code int) *NotifyBuildStartDefault {
	return &NotifyBuildStartDefault{
		_statusCode: code,
	}
}

/*NotifyBuildStartDefault handles this case with default header values.

error
*/
type NotifyBuildStartDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the notify build start default response
func (o *NotifyBuildStartDefault) Code() int {
	return o._statusCode
}

func (o *NotifyBuildStartDefault) Error() string {
	return fmt.Sprintf("[POST /builds/{build_id}/start][%d] notifyBuildStart default  %+v", o._statusCode, o.Payload)
}

func (o *NotifyBuildStartDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *NotifyBuildStartDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
