// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// NewPurgeSiteCacheParams creates a new PurgeSiteCacheParams object
// with the default values initialized.
func NewPurgeSiteCacheParams() *PurgeSiteCacheParams {
	var ()
	return &PurgeSiteCacheParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPurgeSiteCacheParamsWithTimeout creates a new PurgeSiteCacheParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPurgeSiteCacheParamsWithTimeout(timeout time.Duration) *PurgeSiteCacheParams {
	var ()
	return &PurgeSiteCacheParams{

		timeout: timeout,
	}
}

// NewPurgeSiteCacheParamsWithContext creates a new PurgeSiteCacheParams object
// with the default values initialized, and the ability to set a context for a request
func NewPurgeSiteCacheParamsWithContext(ctx context.Context) *PurgeSiteCacheParams {
	var ()
	return &PurgeSiteCacheParams{

		Context: ctx,
	}
}

// NewPurgeSiteCacheParamsWithHTTPClient creates a new PurgeSiteCacheParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPurgeSiteCacheParamsWithHTTPClient(client *http.Client) *PurgeSiteCacheParams {
	var ()
	return &PurgeSiteCacheParams{
		HTTPClient: client,
	}
}

/*
PurgeSiteCacheParams contains all the parameters to send to the API endpoint
for the purge site cache operation typically these are written to a http.Request
*/
type PurgeSiteCacheParams struct {

	/*Payload*/
	Payload *models.Purge

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the purge site cache params
func (o *PurgeSiteCacheParams) WithTimeout(timeout time.Duration) *PurgeSiteCacheParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the purge site cache params
func (o *PurgeSiteCacheParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the purge site cache params
func (o *PurgeSiteCacheParams) WithContext(ctx context.Context) *PurgeSiteCacheParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the purge site cache params
func (o *PurgeSiteCacheParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the purge site cache params
func (o *PurgeSiteCacheParams) WithHTTPClient(client *http.Client) *PurgeSiteCacheParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the purge site cache params
func (o *PurgeSiteCacheParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPayload adds the payload to the purge site cache params
func (o *PurgeSiteCacheParams) WithPayload(payload *models.Purge) *PurgeSiteCacheParams {
	o.SetPayload(payload)
	return o
}

// SetPayload adds the payload to the purge site cache params
func (o *PurgeSiteCacheParams) SetPayload(payload *models.Purge) {
	o.Payload = payload
}

// WriteToRequest writes these params to a swagger request
func (o *PurgeSiteCacheParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Payload != nil {
		if err := r.SetBodyParam(o.Payload); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
