// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoveAccountMemberParams creates a new RemoveAccountMemberParams object
// with the default values initialized.
func NewRemoveAccountMemberParams() *RemoveAccountMemberParams {
	var ()
	return &RemoveAccountMemberParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveAccountMemberParamsWithTimeout creates a new RemoveAccountMemberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveAccountMemberParamsWithTimeout(timeout time.Duration) *RemoveAccountMemberParams {
	var ()
	return &RemoveAccountMemberParams{

		timeout: timeout,
	}
}

// NewRemoveAccountMemberParamsWithContext creates a new RemoveAccountMemberParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveAccountMemberParamsWithContext(ctx context.Context) *RemoveAccountMemberParams {
	var ()
	return &RemoveAccountMemberParams{

		Context: ctx,
	}
}

// NewRemoveAccountMemberParamsWithHTTPClient creates a new RemoveAccountMemberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveAccountMemberParamsWithHTTPClient(client *http.Client) *RemoveAccountMemberParams {
	var ()
	return &RemoveAccountMemberParams{
		HTTPClient: client,
	}
}

/*
RemoveAccountMemberParams contains all the parameters to send to the API endpoint
for the remove account member operation typically these are written to a http.Request
*/
type RemoveAccountMemberParams struct {

	/*AccountSlug*/
	AccountSlug string
	/*MemberID*/
	MemberID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove account member params
func (o *RemoveAccountMemberParams) WithTimeout(timeout time.Duration) *RemoveAccountMemberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove account member params
func (o *RemoveAccountMemberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove account member params
func (o *RemoveAccountMemberParams) WithContext(ctx context.Context) *RemoveAccountMemberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove account member params
func (o *RemoveAccountMemberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove account member params
func (o *RemoveAccountMemberParams) WithHTTPClient(client *http.Client) *RemoveAccountMemberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove account member params
func (o *RemoveAccountMemberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAccountSlug adds the accountSlug to the remove account member params
func (o *RemoveAccountMemberParams) WithAccountSlug(accountSlug string) *RemoveAccountMemberParams {
	o.SetAccountSlug(accountSlug)
	return o
}

// SetAccountSlug adds the accountSlug to the remove account member params
func (o *RemoveAccountMemberParams) SetAccountSlug(accountSlug string) {
	o.AccountSlug = accountSlug
}

// WithMemberID adds the memberID to the remove account member params
func (o *RemoveAccountMemberParams) WithMemberID(memberID string) *RemoveAccountMemberParams {
	o.SetMemberID(memberID)
	return o
}

// SetMemberID adds the memberId to the remove account member params
func (o *RemoveAccountMemberParams) SetMemberID(memberID string) {
	o.MemberID = memberID
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveAccountMemberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param account_slug
	if err := r.SetPathParam("account_slug", o.AccountSlug); err != nil {
		return err
	}

	// path param member_id
	if err := r.SetPathParam("member_id", o.MemberID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
