// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// RollbackSiteDeployReader is a Reader for the RollbackSiteDeploy structure.
type RollbackSiteDeployReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RollbackSiteDeployReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRollbackSiteDeployNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewRollbackSiteDeployDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewRollbackSiteDeployNoContent creates a RollbackSiteDeployNoContent with default headers values
func NewRollbackSiteDeployNoContent() *RollbackSiteDeployNoContent {
	return &RollbackSiteDeployNoContent{}
}

/*RollbackSiteDeployNoContent handles this case with default header values.

No content
*/
type RollbackSiteDeployNoContent struct {
}

func (o *RollbackSiteDeployNoContent) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/rollback][%d] rollbackSiteDeployNoContent ", 204)
}

func (o *RollbackSiteDeployNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRollbackSiteDeployDefault creates a RollbackSiteDeployDefault with default headers values
func NewRollbackSiteDeployDefault(code int) *RollbackSiteDeployDefault {
	return &RollbackSiteDeployDefault{
		_statusCode: code,
	}
}

/*RollbackSiteDeployDefault handles this case with default header values.

error
*/
type RollbackSiteDeployDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the rollback site deploy default response
func (o *RollbackSiteDeployDefault) Code() int {
	return o._statusCode
}

func (o *RollbackSiteDeployDefault) Error() string {
	return fmt.Sprintf("[PUT /sites/{site_id}/rollback][%d] rollbackSiteDeploy default  %+v", o._statusCode, o.Payload)
}

func (o *RollbackSiteDeployDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *RollbackSiteDeployDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
