// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// NewSetSiteDatabaseBranchComputeSettingsParams creates a new SetSiteDatabaseBranchComputeSettingsParams object
// with the default values initialized.
func NewSetSiteDatabaseBranchComputeSettingsParams() *SetSiteDatabaseBranchComputeSettingsParams {
	var ()
	return &SetSiteDatabaseBranchComputeSettingsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSetSiteDatabaseBranchComputeSettingsParamsWithTimeout creates a new SetSiteDatabaseBranchComputeSettingsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSetSiteDatabaseBranchComputeSettingsParamsWithTimeout(timeout time.Duration) *SetSiteDatabaseBranchComputeSettingsParams {
	var ()
	return &SetSiteDatabaseBranchComputeSettingsParams{

		timeout: timeout,
	}
}

// NewSetSiteDatabaseBranchComputeSettingsParamsWithContext creates a new SetSiteDatabaseBranchComputeSettingsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSetSiteDatabaseBranchComputeSettingsParamsWithContext(ctx context.Context) *SetSiteDatabaseBranchComputeSettingsParams {
	var ()
	return &SetSiteDatabaseBranchComputeSettingsParams{

		Context: ctx,
	}
}

// NewSetSiteDatabaseBranchComputeSettingsParamsWithHTTPClient creates a new SetSiteDatabaseBranchComputeSettingsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSetSiteDatabaseBranchComputeSettingsParamsWithHTTPClient(client *http.Client) *SetSiteDatabaseBranchComputeSettingsParams {
	var ()
	return &SetSiteDatabaseBranchComputeSettingsParams{
		HTTPClient: client,
	}
}

/*
SetSiteDatabaseBranchComputeSettingsParams contains all the parameters to send to the API endpoint
for the set site database branch compute settings operation typically these are written to a http.Request
*/
type SetSiteDatabaseBranchComputeSettingsParams struct {

	/*BranchID
	  The branch ID

	*/
	BranchID string
	/*ComputeSettings*/
	ComputeSettings *models.DatabaseComputeSettingsRequest
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) WithTimeout(timeout time.Duration) *SetSiteDatabaseBranchComputeSettingsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) WithContext(ctx context.Context) *SetSiteDatabaseBranchComputeSettingsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) WithHTTPClient(client *http.Client) *SetSiteDatabaseBranchComputeSettingsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBranchID adds the branchID to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) WithBranchID(branchID string) *SetSiteDatabaseBranchComputeSettingsParams {
	o.SetBranchID(branchID)
	return o
}

// SetBranchID adds the branchId to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) SetBranchID(branchID string) {
	o.BranchID = branchID
}

// WithComputeSettings adds the computeSettings to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) WithComputeSettings(computeSettings *models.DatabaseComputeSettingsRequest) *SetSiteDatabaseBranchComputeSettingsParams {
	o.SetComputeSettings(computeSettings)
	return o
}

// SetComputeSettings adds the computeSettings to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) SetComputeSettings(computeSettings *models.DatabaseComputeSettingsRequest) {
	o.ComputeSettings = computeSettings
}

// WithSiteID adds the siteID to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) WithSiteID(siteID string) *SetSiteDatabaseBranchComputeSettingsParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the set site database branch compute settings params
func (o *SetSiteDatabaseBranchComputeSettingsParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *SetSiteDatabaseBranchComputeSettingsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param branch_id
	if err := r.SetPathParam("branch_id", o.BranchID); err != nil {
		return err
	}

	if o.ComputeSettings != nil {
		if err := r.SetBodyParam(o.ComputeSettings); err != nil {
			return err
		}
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
