// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShowTicketParams creates a new ShowTicketParams object
// with the default values initialized.
func NewShowTicketParams() *ShowTicketParams {
	var ()
	return &ShowTicketParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowTicketParamsWithTimeout creates a new ShowTicketParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowTicketParamsWithTimeout(timeout time.Duration) *ShowTicketParams {
	var ()
	return &ShowTicketParams{

		timeout: timeout,
	}
}

// NewShowTicketParamsWithContext creates a new ShowTicketParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowTicketParamsWithContext(ctx context.Context) *ShowTicketParams {
	var ()
	return &ShowTicketParams{

		Context: ctx,
	}
}

// NewShowTicketParamsWithHTTPClient creates a new ShowTicketParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowTicketParamsWithHTTPClient(client *http.Client) *ShowTicketParams {
	var ()
	return &ShowTicketParams{
		HTTPClient: client,
	}
}

/*ShowTicketParams contains all the parameters to send to the API endpoint
for the show ticket operation typically these are written to a http.Request
*/
type ShowTicketParams struct {

	/*TicketID*/
	TicketID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show ticket params
func (o *ShowTicketParams) WithTimeout(timeout time.Duration) *ShowTicketParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show ticket params
func (o *ShowTicketParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show ticket params
func (o *ShowTicketParams) WithContext(ctx context.Context) *ShowTicketParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show ticket params
func (o *ShowTicketParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show ticket params
func (o *ShowTicketParams) WithHTTPClient(client *http.Client) *ShowTicketParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show ticket params
func (o *ShowTicketParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTicketID adds the ticketID to the show ticket params
func (o *ShowTicketParams) WithTicketID(ticketID string) *ShowTicketParams {
	o.SetTicketID(ticketID)
	return o
}

// SetTicketID adds the ticketId to the show ticket params
func (o *ShowTicketParams) SetTicketID(ticketID string) {
	o.TicketID = ticketID
}

// WriteToRequest writes these params to a swagger request
func (o *ShowTicketParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ticket_id
	if err := r.SetPathParam("ticket_id", o.TicketID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
