// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShowServiceParams creates a new ShowServiceParams object
// with the default values initialized.
func NewShowServiceParams() *ShowServiceParams {
	var ()
	return &ShowServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowServiceParamsWithTimeout creates a new ShowServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowServiceParamsWithTimeout(timeout time.Duration) *ShowServiceParams {
	var ()
	return &ShowServiceParams{

		timeout: timeout,
	}
}

// NewShowServiceParamsWithContext creates a new ShowServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowServiceParamsWithContext(ctx context.Context) *ShowServiceParams {
	var ()
	return &ShowServiceParams{

		Context: ctx,
	}
}

// NewShowServiceParamsWithHTTPClient creates a new ShowServiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowServiceParamsWithHTTPClient(client *http.Client) *ShowServiceParams {
	var ()
	return &ShowServiceParams{
		HTTPClient: client,
	}
}

/*ShowServiceParams contains all the parameters to send to the API endpoint
for the show service operation typically these are written to a http.Request
*/
type ShowServiceParams struct {

	/*AddonName*/
	AddonName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show service params
func (o *ShowServiceParams) WithTimeout(timeout time.Duration) *ShowServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show service params
func (o *ShowServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show service params
func (o *ShowServiceParams) WithContext(ctx context.Context) *ShowServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show service params
func (o *ShowServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show service params
func (o *ShowServiceParams) WithHTTPClient(client *http.Client) *ShowServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show service params
func (o *ShowServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddonName adds the addonName to the show service params
func (o *ShowServiceParams) WithAddonName(addonName string) *ShowServiceParams {
	o.SetAddonName(addonName)
	return o
}

// SetAddonName adds the addonName to the show service params
func (o *ShowServiceParams) SetAddonName(addonName string) {
	o.AddonName = addonName
}

// WriteToRequest writes these params to a swagger request
func (o *ShowServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param addonName
	if err := r.SetPathParam("addonName", o.AddonName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
