// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewShowServiceInstanceParams creates a new ShowServiceInstanceParams object
// with the default values initialized.
func NewShowServiceInstanceParams() *ShowServiceInstanceParams {
	var ()
	return &ShowServiceInstanceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewShowServiceInstanceParamsWithTimeout creates a new ShowServiceInstanceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewShowServiceInstanceParamsWithTimeout(timeout time.Duration) *ShowServiceInstanceParams {
	var ()
	return &ShowServiceInstanceParams{

		timeout: timeout,
	}
}

// NewShowServiceInstanceParamsWithContext creates a new ShowServiceInstanceParams object
// with the default values initialized, and the ability to set a context for a request
func NewShowServiceInstanceParamsWithContext(ctx context.Context) *ShowServiceInstanceParams {
	var ()
	return &ShowServiceInstanceParams{

		Context: ctx,
	}
}

// NewShowServiceInstanceParamsWithHTTPClient creates a new ShowServiceInstanceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewShowServiceInstanceParamsWithHTTPClient(client *http.Client) *ShowServiceInstanceParams {
	var ()
	return &ShowServiceInstanceParams{
		HTTPClient: client,
	}
}

/*ShowServiceInstanceParams contains all the parameters to send to the API endpoint
for the show service instance operation typically these are written to a http.Request
*/
type ShowServiceInstanceParams struct {

	/*Addon*/
	Addon string
	/*InstanceID*/
	InstanceID string
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the show service instance params
func (o *ShowServiceInstanceParams) WithTimeout(timeout time.Duration) *ShowServiceInstanceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the show service instance params
func (o *ShowServiceInstanceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the show service instance params
func (o *ShowServiceInstanceParams) WithContext(ctx context.Context) *ShowServiceInstanceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the show service instance params
func (o *ShowServiceInstanceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the show service instance params
func (o *ShowServiceInstanceParams) WithHTTPClient(client *http.Client) *ShowServiceInstanceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the show service instance params
func (o *ShowServiceInstanceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAddon adds the addon to the show service instance params
func (o *ShowServiceInstanceParams) WithAddon(addon string) *ShowServiceInstanceParams {
	o.SetAddon(addon)
	return o
}

// SetAddon adds the addon to the show service instance params
func (o *ShowServiceInstanceParams) SetAddon(addon string) {
	o.Addon = addon
}

// WithInstanceID adds the instanceID to the show service instance params
func (o *ShowServiceInstanceParams) WithInstanceID(instanceID string) *ShowServiceInstanceParams {
	o.SetInstanceID(instanceID)
	return o
}

// SetInstanceID adds the instanceId to the show service instance params
func (o *ShowServiceInstanceParams) SetInstanceID(instanceID string) {
	o.InstanceID = instanceID
}

// WithSiteID adds the siteID to the show service instance params
func (o *ShowServiceInstanceParams) WithSiteID(siteID string) *ShowServiceInstanceParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the show service instance params
func (o *ShowServiceInstanceParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *ShowServiceInstanceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param addon
	if err := r.SetPathParam("addon", o.Addon); err != nil {
		return err
	}

	// path param instance_id
	if err := r.SetPathParam("instance_id", o.InstanceID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
