// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// TransferDNSZoneReader is a Reader for the TransferDNSZone structure.
type TransferDNSZoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TransferDNSZoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTransferDNSZoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewTransferDNSZoneDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewTransferDNSZoneOK creates a TransferDNSZoneOK with default headers values
func NewTransferDNSZoneOK() *TransferDNSZoneOK {
	return &TransferDNSZoneOK{}
}

/*TransferDNSZoneOK handles this case with default header values.

transfer a DNS zone to another account
*/
type TransferDNSZoneOK struct {
	Payload *models.DNSZone
}

func (o *TransferDNSZoneOK) Error() string {
	return fmt.Sprintf("[PUT /dns_zones/{zone_id}/transfer][%d] transferDnsZoneOK  %+v", 200, o.Payload)
}

func (o *TransferDNSZoneOK) GetPayload() *models.DNSZone {
	return o.Payload
}

func (o *TransferDNSZoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DNSZone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewTransferDNSZoneDefault creates a TransferDNSZoneDefault with default headers values
func NewTransferDNSZoneDefault(code int) *TransferDNSZoneDefault {
	return &TransferDNSZoneDefault{
		_statusCode: code,
	}
}

/*TransferDNSZoneDefault handles this case with default header values.

error
*/
type TransferDNSZoneDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the transfer Dns zone default response
func (o *TransferDNSZoneDefault) Code() int {
	return o._statusCode
}

func (o *TransferDNSZoneDefault) Error() string {
	return fmt.Sprintf("[PUT /dns_zones/{zone_id}/transfer][%d] transferDnsZone default  %+v", o._statusCode, o.Payload)
}

func (o *TransferDNSZoneDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *TransferDNSZoneDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
