// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// UnlockDeployReader is a Reader for the UnlockDeploy structure.
type UnlockDeployReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnlockDeployReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUnlockDeployOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUnlockDeployDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUnlockDeployOK creates a UnlockDeployOK with default headers values
func NewUnlockDeployOK() *UnlockDeployOK {
	return &UnlockDeployOK{}
}

/*UnlockDeployOK handles this case with default header values.

OK
*/
type UnlockDeployOK struct {
	Payload *models.Deploy
}

func (o *UnlockDeployOK) Error() string {
	return fmt.Sprintf("[POST /deploys/{deploy_id}/unlock][%d] unlockDeployOK  %+v", 200, o.Payload)
}

func (o *UnlockDeployOK) GetPayload() *models.Deploy {
	return o.Payload
}

func (o *UnlockDeployOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Deploy)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUnlockDeployDefault creates a UnlockDeployDefault with default headers values
func NewUnlockDeployDefault(code int) *UnlockDeployDefault {
	return &UnlockDeployDefault{
		_statusCode: code,
	}
}

/*UnlockDeployDefault handles this case with default header values.

error
*/
type UnlockDeployDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the unlock deploy default response
func (o *UnlockDeployDefault) Code() int {
	return o._statusCode
}

func (o *UnlockDeployDefault) Error() string {
	return fmt.Sprintf("[POST /deploys/{deploy_id}/unlock][%d] unlockDeploy default  %+v", o._statusCode, o.Payload)
}

func (o *UnlockDeployDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UnlockDeployDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
