package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUnlockDeployParams creates a new UnlockDeployParams object
// with the default values initialized.
func NewUnlockDeployParams() *UnlockDeployParams {
	var ()
	return &UnlockDeployParams{}
}

/*UnlockDeployParams contains all the parameters to send to the API endpoint
for the unlock deploy operation typically these are written to a http.Request
*/
type UnlockDeployParams struct {

	/*DeployID*/
	DeployID string
}

// WithDeployID adds the deployId to the unlock deploy params
func (o *UnlockDeployParams) WithDeployID(DeployID string) *UnlockDeployParams {
	o.DeployID = DeployID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UnlockDeployParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param deploy_id
	if err := r.SetPathParam("deploy_id", o.DeployID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
