// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// UpdateAccountReader is a Reader for the UpdateAccount structure.
type UpdateAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAccountOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateAccountDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAccountOK creates a UpdateAccountOK with default headers values
func NewUpdateAccountOK() *UpdateAccountOK {
	return &UpdateAccountOK{}
}

/*UpdateAccountOK handles this case with default header values.

OK
*/
type UpdateAccountOK struct {
	Payload *models.AccountMembership
}

func (o *UpdateAccountOK) Error() string {
	return fmt.Sprintf("[PUT /accounts/{account_id}][%d] updateAccountOK  %+v", 200, o.Payload)
}

func (o *UpdateAccountOK) GetPayload() *models.AccountMembership {
	return o.Payload
}

func (o *UpdateAccountOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AccountMembership)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAccountDefault creates a UpdateAccountDefault with default headers values
func NewUpdateAccountDefault(code int) *UpdateAccountDefault {
	return &UpdateAccountDefault{
		_statusCode: code,
	}
}

/*UpdateAccountDefault handles this case with default header values.

error
*/
type UpdateAccountDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update account default response
func (o *UpdateAccountDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAccountDefault) Error() string {
	return fmt.Sprintf("[PUT /accounts/{account_id}][%d] updateAccount default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAccountDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateAccountDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
