// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// NewUpdateDevServerStateParams creates a new UpdateDevServerStateParams object
// with the default values initialized.
func NewUpdateDevServerStateParams() *UpdateDevServerStateParams {
	var ()
	return &UpdateDevServerStateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDevServerStateParamsWithTimeout creates a new UpdateDevServerStateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateDevServerStateParamsWithTimeout(timeout time.Duration) *UpdateDevServerStateParams {
	var ()
	return &UpdateDevServerStateParams{

		timeout: timeout,
	}
}

// NewUpdateDevServerStateParamsWithContext creates a new UpdateDevServerStateParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateDevServerStateParamsWithContext(ctx context.Context) *UpdateDevServerStateParams {
	var ()
	return &UpdateDevServerStateParams{

		Context: ctx,
	}
}

// NewUpdateDevServerStateParamsWithHTTPClient creates a new UpdateDevServerStateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateDevServerStateParamsWithHTTPClient(client *http.Client) *UpdateDevServerStateParams {
	var ()
	return &UpdateDevServerStateParams{
		HTTPClient: client,
	}
}

/*
UpdateDevServerStateParams contains all the parameters to send to the API endpoint
for the update dev server state operation typically these are written to a http.Request
*/
type UpdateDevServerStateParams struct {

	/*Body*/
	Body *models.UpdateDevServerStateParamsBody
	/*DevServerID*/
	DevServerID string
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update dev server state params
func (o *UpdateDevServerStateParams) WithTimeout(timeout time.Duration) *UpdateDevServerStateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update dev server state params
func (o *UpdateDevServerStateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update dev server state params
func (o *UpdateDevServerStateParams) WithContext(ctx context.Context) *UpdateDevServerStateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update dev server state params
func (o *UpdateDevServerStateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update dev server state params
func (o *UpdateDevServerStateParams) WithHTTPClient(client *http.Client) *UpdateDevServerStateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update dev server state params
func (o *UpdateDevServerStateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the update dev server state params
func (o *UpdateDevServerStateParams) WithBody(body *models.UpdateDevServerStateParamsBody) *UpdateDevServerStateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the update dev server state params
func (o *UpdateDevServerStateParams) SetBody(body *models.UpdateDevServerStateParamsBody) {
	o.Body = body
}

// WithDevServerID adds the devServerID to the update dev server state params
func (o *UpdateDevServerStateParams) WithDevServerID(devServerID string) *UpdateDevServerStateParams {
	o.SetDevServerID(devServerID)
	return o
}

// SetDevServerID adds the devServerId to the update dev server state params
func (o *UpdateDevServerStateParams) SetDevServerID(devServerID string) {
	o.DevServerID = devServerID
}

// WithSiteID adds the siteID to the update dev server state params
func (o *UpdateDevServerStateParams) WithSiteID(siteID string) *UpdateDevServerStateParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the update dev server state params
func (o *UpdateDevServerStateParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDevServerStateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param dev_server_id
	if err := r.SetPathParam("dev_server_id", o.DevServerID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
