// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// NewUpdateDeployValidationsParams creates a new UpdateDeployValidationsParams object
// with the default values initialized.
func NewUpdateDeployValidationsParams() *UpdateDeployValidationsParams {
	var ()
	return &UpdateDeployValidationsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateDeployValidationsParamsWithTimeout creates a new UpdateDeployValidationsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateDeployValidationsParamsWithTimeout(timeout time.Duration) *UpdateDeployValidationsParams {
	var ()
	return &UpdateDeployValidationsParams{

		timeout: timeout,
	}
}

// NewUpdateDeployValidationsParamsWithContext creates a new UpdateDeployValidationsParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateDeployValidationsParamsWithContext(ctx context.Context) *UpdateDeployValidationsParams {
	var ()
	return &UpdateDeployValidationsParams{

		Context: ctx,
	}
}

// NewUpdateDeployValidationsParamsWithHTTPClient creates a new UpdateDeployValidationsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateDeployValidationsParamsWithHTTPClient(client *http.Client) *UpdateDeployValidationsParams {
	var ()
	return &UpdateDeployValidationsParams{
		HTTPClient: client,
	}
}

/*
UpdateDeployValidationsParams contains all the parameters to send to the API endpoint
for the update deploy validations operation typically these are written to a http.Request
*/
type UpdateDeployValidationsParams struct {

	/*DeployID
	  The ID of the deploy

	*/
	DeployID string
	/*Report*/
	Report *models.UpdateDeployValidationsParamsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update deploy validations params
func (o *UpdateDeployValidationsParams) WithTimeout(timeout time.Duration) *UpdateDeployValidationsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update deploy validations params
func (o *UpdateDeployValidationsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update deploy validations params
func (o *UpdateDeployValidationsParams) WithContext(ctx context.Context) *UpdateDeployValidationsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update deploy validations params
func (o *UpdateDeployValidationsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update deploy validations params
func (o *UpdateDeployValidationsParams) WithHTTPClient(client *http.Client) *UpdateDeployValidationsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update deploy validations params
func (o *UpdateDeployValidationsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDeployID adds the deployID to the update deploy validations params
func (o *UpdateDeployValidationsParams) WithDeployID(deployID string) *UpdateDeployValidationsParams {
	o.SetDeployID(deployID)
	return o
}

// SetDeployID adds the deployId to the update deploy validations params
func (o *UpdateDeployValidationsParams) SetDeployID(deployID string) {
	o.DeployID = deployID
}

// WithReport adds the report to the update deploy validations params
func (o *UpdateDeployValidationsParams) WithReport(report *models.UpdateDeployValidationsParamsBody) *UpdateDeployValidationsParams {
	o.SetReport(report)
	return o
}

// SetReport adds the report to the update deploy validations params
func (o *UpdateDeployValidationsParams) SetReport(report *models.UpdateDeployValidationsParamsBody) {
	o.Report = report
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateDeployValidationsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param deploy_id
	if err := r.SetPathParam("deploy_id", o.DeployID); err != nil {
		return err
	}

	if o.Report != nil {
		if err := r.SetBodyParam(o.Report); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
