package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/go/models"
)

// NewUpdateSiteDeployParams creates a new UpdateSiteDeployParams object
// with the default values initialized.
func NewUpdateSiteDeployParams() *UpdateSiteDeployParams {
	var ()
	return &UpdateSiteDeployParams{}
}

/*UpdateSiteDeployParams contains all the parameters to send to the API endpoint
for the update site deploy operation typically these are written to a http.Request
*/
type UpdateSiteDeployParams struct {

	/*Deploy*/
	Deploy *models.DeployFiles
	/*DeployID*/
	DeployID string
	/*SiteID*/
	SiteID string
}

// WithDeploy adds the deploy to the update site deploy params
func (o *UpdateSiteDeployParams) WithDeploy(Deploy *models.DeployFiles) *UpdateSiteDeployParams {
	o.Deploy = Deploy
	return o
}

// WithDeployID adds the deployId to the update site deploy params
func (o *UpdateSiteDeployParams) WithDeployID(DeployID string) *UpdateSiteDeployParams {
	o.DeployID = DeployID
	return o
}

// WithSiteID adds the siteId to the update site deploy params
func (o *UpdateSiteDeployParams) WithSiteID(SiteID string) *UpdateSiteDeployParams {
	o.SiteID = SiteID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateSiteDeployParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	if o.Deploy == nil {
		o.Deploy = new(models.DeployFiles)
	}

	if err := r.SetBodyParam(o.Deploy); err != nil {
		return err
	}

	// path param deploy_id
	if err := r.SetPathParam("deploy_id", o.DeployID); err != nil {
		return err
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
