// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// UpdateDeployValidationsReader is a Reader for the UpdateDeployValidations structure.
type UpdateDeployValidationsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateDeployValidationsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateDeployValidationsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateDeployValidationsOK creates a UpdateDeployValidationsOK with default headers values
func NewUpdateDeployValidationsOK() *UpdateDeployValidationsOK {
	return &UpdateDeployValidationsOK{}
}

/*
UpdateDeployValidationsOK handles this case with default header values.

OK
*/
type UpdateDeployValidationsOK struct {
	Payload *models.DeployValidationsReport
}

func (o *UpdateDeployValidationsOK) Error() string {
	return fmt.Sprintf("[PATCH /deploys/{deploy_id}/validations_report][%d] updateDeployValidationsOK  %+v", 200, o.Payload)
}

func (o *UpdateDeployValidationsOK) GetPayload() *models.DeployValidationsReport {
	return o.Payload
}

func (o *UpdateDeployValidationsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeployValidationsReport)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
