// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUpdateAgentRunnerParams creates a new UpdateAgentRunnerParams object
// with the default values initialized.
func NewUpdateAgentRunnerParams() *UpdateAgentRunnerParams {
	var ()
	return &UpdateAgentRunnerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAgentRunnerParamsWithTimeout creates a new UpdateAgentRunnerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAgentRunnerParamsWithTimeout(timeout time.Duration) *UpdateAgentRunnerParams {
	var ()
	return &UpdateAgentRunnerParams{

		timeout: timeout,
	}
}

// NewUpdateAgentRunnerParamsWithContext creates a new UpdateAgentRunnerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAgentRunnerParamsWithContext(ctx context.Context) *UpdateAgentRunnerParams {
	var ()
	return &UpdateAgentRunnerParams{

		Context: ctx,
	}
}

// NewUpdateAgentRunnerParamsWithHTTPClient creates a new UpdateAgentRunnerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAgentRunnerParamsWithHTTPClient(client *http.Client) *UpdateAgentRunnerParams {
	var ()
	return &UpdateAgentRunnerParams{
		HTTPClient: client,
	}
}

/*
UpdateAgentRunnerParams contains all the parameters to send to the API endpoint
for the update agent runner operation typically these are written to a http.Request
*/
type UpdateAgentRunnerParams struct {

	/*AgentRunnerID*/
	AgentRunnerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update agent runner params
func (o *UpdateAgentRunnerParams) WithTimeout(timeout time.Duration) *UpdateAgentRunnerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update agent runner params
func (o *UpdateAgentRunnerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update agent runner params
func (o *UpdateAgentRunnerParams) WithContext(ctx context.Context) *UpdateAgentRunnerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update agent runner params
func (o *UpdateAgentRunnerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update agent runner params
func (o *UpdateAgentRunnerParams) WithHTTPClient(client *http.Client) *UpdateAgentRunnerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update agent runner params
func (o *UpdateAgentRunnerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAgentRunnerID adds the agentRunnerID to the update agent runner params
func (o *UpdateAgentRunnerParams) WithAgentRunnerID(agentRunnerID string) *UpdateAgentRunnerParams {
	o.SetAgentRunnerID(agentRunnerID)
	return o
}

// SetAgentRunnerID adds the agentRunnerId to the update agent runner params
func (o *UpdateAgentRunnerParams) SetAgentRunnerID(agentRunnerID string) {
	o.AgentRunnerID = agentRunnerID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAgentRunnerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param agent_runner_id
	if err := r.SetPathParam("agent_runner_id", o.AgentRunnerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
