// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// NewUpdatePluginParams creates a new UpdatePluginParams object
// with the default values initialized.
func NewUpdatePluginParams() *UpdatePluginParams {
	var ()
	return &UpdatePluginParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePluginParamsWithTimeout creates a new UpdatePluginParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePluginParamsWithTimeout(timeout time.Duration) *UpdatePluginParams {
	var ()
	return &UpdatePluginParams{

		timeout: timeout,
	}
}

// NewUpdatePluginParamsWithContext creates a new UpdatePluginParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePluginParamsWithContext(ctx context.Context) *UpdatePluginParams {
	var ()
	return &UpdatePluginParams{

		Context: ctx,
	}
}

// NewUpdatePluginParamsWithHTTPClient creates a new UpdatePluginParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePluginParamsWithHTTPClient(client *http.Client) *UpdatePluginParams {
	var ()
	return &UpdatePluginParams{
		HTTPClient: client,
	}
}

/*UpdatePluginParams contains all the parameters to send to the API endpoint
for the update plugin operation typically these are written to a http.Request
*/
type UpdatePluginParams struct {

	/*Package*/
	Package string
	/*PluginParams*/
	PluginParams *models.PluginParams
	/*SiteID*/
	SiteID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update plugin params
func (o *UpdatePluginParams) WithTimeout(timeout time.Duration) *UpdatePluginParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update plugin params
func (o *UpdatePluginParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update plugin params
func (o *UpdatePluginParams) WithContext(ctx context.Context) *UpdatePluginParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update plugin params
func (o *UpdatePluginParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update plugin params
func (o *UpdatePluginParams) WithHTTPClient(client *http.Client) *UpdatePluginParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update plugin params
func (o *UpdatePluginParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPackage adds the packageVar to the update plugin params
func (o *UpdatePluginParams) WithPackage(packageVar string) *UpdatePluginParams {
	o.SetPackage(packageVar)
	return o
}

// SetPackage adds the package to the update plugin params
func (o *UpdatePluginParams) SetPackage(packageVar string) {
	o.Package = packageVar
}

// WithPluginParams adds the pluginParams to the update plugin params
func (o *UpdatePluginParams) WithPluginParams(pluginParams *models.PluginParams) *UpdatePluginParams {
	o.SetPluginParams(pluginParams)
	return o
}

// SetPluginParams adds the pluginParams to the update plugin params
func (o *UpdatePluginParams) SetPluginParams(pluginParams *models.PluginParams) {
	o.PluginParams = pluginParams
}

// WithSiteID adds the siteID to the update plugin params
func (o *UpdatePluginParams) WithSiteID(siteID string) *UpdatePluginParams {
	o.SetSiteID(siteID)
	return o
}

// SetSiteID adds the siteId to the update plugin params
func (o *UpdatePluginParams) SetSiteID(siteID string) {
	o.SiteID = siteID
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePluginParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param package
	if err := r.SetPathParam("package", o.Package); err != nil {
		return err
	}

	if o.PluginParams != nil {
		if err := r.SetBodyParam(o.PluginParams); err != nil {
			return err
		}
	}

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
