// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// UpdateAgentRunnerReader is a Reader for the UpdateAgentRunner structure.
type UpdateAgentRunnerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateAgentRunnerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUpdateAgentRunnerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUpdateAgentRunnerDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUpdateAgentRunnerOK creates a UpdateAgentRunnerOK with default headers values
func NewUpdateAgentRunnerOK() *UpdateAgentRunnerOK {
	return &UpdateAgentRunnerOK{}
}

/*
UpdateAgentRunnerOK handles this case with default header values.

OK
*/
type UpdateAgentRunnerOK struct {
	Payload *models.AgentRunner
}

func (o *UpdateAgentRunnerOK) Error() string {
	return fmt.Sprintf("[PATCH /agent_runners/{agent_runner_id}][%d] updateAgentRunnerOK  %+v", 200, o.Payload)
}

func (o *UpdateAgentRunnerOK) GetPayload() *models.AgentRunner {
	return o.Payload
}

func (o *UpdateAgentRunnerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AgentRunner)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUpdateAgentRunnerDefault creates a UpdateAgentRunnerDefault with default headers values
func NewUpdateAgentRunnerDefault(code int) *UpdateAgentRunnerDefault {
	return &UpdateAgentRunnerDefault{
		_statusCode: code,
	}
}

/*
UpdateAgentRunnerDefault handles this case with default header values.

error
*/
type UpdateAgentRunnerDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the update agent runner default response
func (o *UpdateAgentRunnerDefault) Code() int {
	return o._statusCode
}

func (o *UpdateAgentRunnerDefault) Error() string {
	return fmt.Sprintf("[PATCH /agent_runners/{agent_runner_id}][%d] updateAgentRunner default  %+v", o._statusCode, o.Payload)
}

func (o *UpdateAgentRunnerDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UpdateAgentRunnerDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
