// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"io"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewUploadDeployEdgeFunctionParams creates a new UploadDeployEdgeFunctionParams object
// with the default values initialized.
func NewUploadDeployEdgeFunctionParams() *UploadDeployEdgeFunctionParams {
	var ()
	return &UploadDeployEdgeFunctionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUploadDeployEdgeFunctionParamsWithTimeout creates a new UploadDeployEdgeFunctionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUploadDeployEdgeFunctionParamsWithTimeout(timeout time.Duration) *UploadDeployEdgeFunctionParams {
	var ()
	return &UploadDeployEdgeFunctionParams{

		timeout: timeout,
	}
}

// NewUploadDeployEdgeFunctionParamsWithContext creates a new UploadDeployEdgeFunctionParams object
// with the default values initialized, and the ability to set a context for a request
func NewUploadDeployEdgeFunctionParamsWithContext(ctx context.Context) *UploadDeployEdgeFunctionParams {
	var ()
	return &UploadDeployEdgeFunctionParams{

		Context: ctx,
	}
}

// NewUploadDeployEdgeFunctionParamsWithHTTPClient creates a new UploadDeployEdgeFunctionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUploadDeployEdgeFunctionParamsWithHTTPClient(client *http.Client) *UploadDeployEdgeFunctionParams {
	var ()
	return &UploadDeployEdgeFunctionParams{
		HTTPClient: client,
	}
}

/*
UploadDeployEdgeFunctionParams contains all the parameters to send to the API endpoint
for the upload deploy edge function operation typically these are written to a http.Request
*/
type UploadDeployEdgeFunctionParams struct {

	/*XNfRetryCount*/
	XNfRetryCount *int64
	/*CodeSha*/
	CodeSha string
	/*DeployID*/
	DeployID string
	/*FileBody*/
	FileBody io.ReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithTimeout(timeout time.Duration) *UploadDeployEdgeFunctionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithContext(ctx context.Context) *UploadDeployEdgeFunctionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithHTTPClient(client *http.Client) *UploadDeployEdgeFunctionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXNfRetryCount adds the xNfRetryCount to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithXNfRetryCount(xNfRetryCount *int64) *UploadDeployEdgeFunctionParams {
	o.SetXNfRetryCount(xNfRetryCount)
	return o
}

// SetXNfRetryCount adds the xNfRetryCount to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetXNfRetryCount(xNfRetryCount *int64) {
	o.XNfRetryCount = xNfRetryCount
}

// WithCodeSha adds the codeSha to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithCodeSha(codeSha string) *UploadDeployEdgeFunctionParams {
	o.SetCodeSha(codeSha)
	return o
}

// SetCodeSha adds the codeSha to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetCodeSha(codeSha string) {
	o.CodeSha = codeSha
}

// WithDeployID adds the deployID to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithDeployID(deployID string) *UploadDeployEdgeFunctionParams {
	o.SetDeployID(deployID)
	return o
}

// SetDeployID adds the deployId to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetDeployID(deployID string) {
	o.DeployID = deployID
}

// WithFileBody adds the fileBody to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) WithFileBody(fileBody io.ReadCloser) *UploadDeployEdgeFunctionParams {
	o.SetFileBody(fileBody)
	return o
}

// SetFileBody adds the fileBody to the upload deploy edge function params
func (o *UploadDeployEdgeFunctionParams) SetFileBody(fileBody io.ReadCloser) {
	o.FileBody = fileBody
}

// WriteToRequest writes these params to a swagger request
func (o *UploadDeployEdgeFunctionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.XNfRetryCount != nil {

		// header param X-Nf-Retry-Count
		if err := r.SetHeaderParam("X-Nf-Retry-Count", swag.FormatInt64(*o.XNfRetryCount)); err != nil {
			return err
		}

	}

	// path param code_sha
	if err := r.SetPathParam("code_sha", o.CodeSha); err != nil {
		return err
	}

	// path param deploy_id
	if err := r.SetPathParam("deploy_id", o.DeployID); err != nil {
		return err
	}

	if o.FileBody != nil {
		if err := r.SetBodyParam(o.FileBody); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
