// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/netlify/open-api/v2/go/models"
)

// UploadDeployEdgeFunctionReader is a Reader for the UploadDeployEdgeFunction structure.
type UploadDeployEdgeFunctionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadDeployEdgeFunctionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUploadDeployEdgeFunctionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewUploadDeployEdgeFunctionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewUploadDeployEdgeFunctionOK creates a UploadDeployEdgeFunctionOK with default headers values
func NewUploadDeployEdgeFunctionOK() *UploadDeployEdgeFunctionOK {
	return &UploadDeployEdgeFunctionOK{}
}

/*
UploadDeployEdgeFunctionOK handles this case with default header values.

OK
*/
type UploadDeployEdgeFunctionOK struct {
}

func (o *UploadDeployEdgeFunctionOK) Error() string {
	return fmt.Sprintf("[PUT /deploys/{deploy_id}/edge_functions/{code_sha}][%d] uploadDeployEdgeFunctionOK ", 200)
}

func (o *UploadDeployEdgeFunctionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadDeployEdgeFunctionDefault creates a UploadDeployEdgeFunctionDefault with default headers values
func NewUploadDeployEdgeFunctionDefault(code int) *UploadDeployEdgeFunctionDefault {
	return &UploadDeployEdgeFunctionDefault{
		_statusCode: code,
	}
}

/*
UploadDeployEdgeFunctionDefault handles this case with default header values.

error
*/
type UploadDeployEdgeFunctionDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the upload deploy edge function default response
func (o *UploadDeployEdgeFunctionDefault) Code() int {
	return o._statusCode
}

func (o *UploadDeployEdgeFunctionDefault) Error() string {
	return fmt.Sprintf("[PUT /deploys/{deploy_id}/edge_functions/{code_sha}][%d] uploadDeployEdgeFunction default  %+v", o._statusCode, o.Payload)
}

func (o *UploadDeployEdgeFunctionDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *UploadDeployEdgeFunctionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
