package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteSitesSiteIDSnippetsSnippetIDParams creates a new DeleteSitesSiteIDSnippetsSnippetIDParams object
// with the default values initialized.
func NewDeleteSitesSiteIDSnippetsSnippetIDParams() *DeleteSitesSiteIDSnippetsSnippetIDParams {
	var ()
	return &DeleteSitesSiteIDSnippetsSnippetIDParams{}
}

/*DeleteSitesSiteIDSnippetsSnippetIDParams contains all the parameters to send to the API endpoint
for the delete sites site ID snippets snippet ID operation typically these are written to a http.Request
*/
type DeleteSitesSiteIDSnippetsSnippetIDParams struct {

	/*SiteID*/
	SiteID string
	/*SnippetID*/
	SnippetID string
}

// WithSiteID adds the siteId to the delete sites site ID snippets snippet ID params
func (o *DeleteSitesSiteIDSnippetsSnippetIDParams) WithSiteID(SiteID string) *DeleteSitesSiteIDSnippetsSnippetIDParams {
	o.SiteID = SiteID
	return o
}

// WithSnippetID adds the snippetId to the delete sites site ID snippets snippet ID params
func (o *DeleteSitesSiteIDSnippetsSnippetIDParams) WithSnippetID(SnippetID string) *DeleteSitesSiteIDSnippetsSnippetIDParams {
	o.SnippetID = SnippetID
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteSitesSiteIDSnippetsSnippetIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	var res []error

	// path param site_id
	if err := r.SetPathParam("site_id", o.SiteID); err != nil {
		return err
	}

	// path param snippet_id
	if err := r.SetPathParam("snippet_id", o.SnippetID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
