package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/netlify/swagger-api/models"
)

// GetHooksReader is a Reader for the GetHooks structure.
type GetHooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetHooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetHooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetHooksDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	}
}

// NewGetHooksOK creates a GetHooksOK with default headers values
func NewGetHooksOK() *GetHooksOK {
	return &GetHooksOK{}
}

/*GetHooksOK handles this case with default header values.

OK
*/
type GetHooksOK struct {
	Payload []models.Hook
}

func (o *GetHooksOK) Error() string {
	return fmt.Sprintf("[GET /hooks][%d] getHooksOK  %+v", 200, o.Payload)
}

func (o *GetHooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetHooksDefault creates a GetHooksDefault with default headers values
func NewGetHooksDefault(code int) *GetHooksDefault {
	return &GetHooksDefault{
		_statusCode: code,
	}
}

/*GetHooksDefault handles this case with default header values.

error
*/
type GetHooksDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get hooks default response
func (o *GetHooksDefault) Code() int {
	return o._statusCode
}

func (o *GetHooksDefault) Error() string {
	return fmt.Sprintf("[GET /hooks][%d] GetHooks default  %+v", o._statusCode, o.Payload)
}

func (o *GetHooksDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
