package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Hook hook

swagger:model hook
*/
type Hook interface{}
